
package com.jamar.serviciohistoriacreditoplus.v1;

import javax.xml.ws.WebFault;
import com.dc.hc2.ws.v1.Fault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "Fault", targetNamespace = "http://ws.hc2.dc.com/v1")
public class HC2PNJException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Fault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public HC2PNJException(String message, Fault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public HC2PNJException(String message, Fault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.dc.hc2.ws.v1.Fault
     */
    public Fault getFaultInfo() {
        return faultInfo;
    }

}
