//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for ChequesType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ChequesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Trimestre" maxOccurs="3">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="cantidadDevueltos" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="valorDevueltos" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="cantidadPagados" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="valorPagados" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChequesType", propOrder = {
    "trimestre"
})
public class ChequesType {

    @XmlElement(name = "Trimestre")
    protected List<ChequesType.Trimestre> trimestre;

    /**
     * Gets the value of the trimestre property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the trimestre property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrimestre().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ChequesType.Trimestre }
     *
     *
     */
    public List<ChequesType.Trimestre> getTrimestre() {
        if (trimestre == null) {
            trimestre = new ArrayList<ChequesType.Trimestre>();
        }
        return this.trimestre;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="cantidadDevueltos" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="valorDevueltos" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="cantidadPagados" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="valorPagados" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Trimestre {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;
        @XmlAttribute(required = true)
        protected int cantidadDevueltos;
        @XmlAttribute(required = true)
        protected double valorDevueltos;
        @XmlAttribute(required = true)
        protected int cantidadPagados;
        @XmlAttribute(required = true)
        protected double valorPagados;

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

        /**
         * Gets the value of the cantidadDevueltos property.
         *
         */
        public int getCantidadDevueltos() {
            return cantidadDevueltos;
        }

        /**
         * Sets the value of the cantidadDevueltos property.
         *
         */
        public void setCantidadDevueltos(int value) {
            this.cantidadDevueltos = value;
        }

        /**
         * Gets the value of the valorDevueltos property.
         *
         */
        public double getValorDevueltos() {
            return valorDevueltos;
        }

        /**
         * Sets the value of the valorDevueltos property.
         *
         */
        public void setValorDevueltos(double value) {
            this.valorDevueltos = value;
        }

        /**
         * Gets the value of the cantidadPagados property.
         *
         */
        public int getCantidadPagados() {
            return cantidadPagados;
        }

        /**
         * Sets the value of the cantidadPagados property.
         *
         */
        public void setCantidadPagados(int value) {
            this.cantidadPagados = value;
        }

        /**
         * Gets the value of the valorPagados property.
         *
         */
        public double getValorPagados() {
            return valorPagados;
        }

        /**
         * Sets the value of the valorPagados property.
         *
         */
        public void setValorPagados(double value) {
            this.valorPagados = value;
        }

    }

}
