//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ComposicionPortafolioType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ComposicionPortafolioType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="TipoCuenta" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Estado" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="calidadDeudor" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                 &lt;attribute name="porcentaje" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComposicionPortafolioType", propOrder = {
    "tipoCuenta"
})
public class ComposicionPortafolioType {

    @XmlElement(name = "TipoCuenta")
    protected List<ComposicionPortafolioType.TipoCuenta> tipoCuenta;

    /**
     * Gets the value of the tipoCuenta property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the tipoCuenta property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipoCuenta().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComposicionPortafolioType.TipoCuenta }
     *
     *
     * @return
     */
    public List<ComposicionPortafolioType.TipoCuenta> getTipoCuenta() {
        if (tipoCuenta == null) {
            tipoCuenta = new ArrayList<ComposicionPortafolioType.TipoCuenta>();
        }
        return this.tipoCuenta;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Estado" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="calidadDeudor" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *       &lt;attribute name="porcentaje" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "estado"
    })
    public static class TipoCuenta {

        @XmlElement(name = "Estado", required = true)
        protected List<ComposicionPortafolioType.TipoCuenta.Estado> estado;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String tipo;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String calidadDeudor;
        @XmlAttribute(required = true)
        protected double porcentaje;
        @XmlAttribute(required = true)
        protected int cantidad;

        /**
         * Gets the value of the estado property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the estado property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEstado().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ComposicionPortafolioType.TipoCuenta.Estado }
         *
         *
         * @return
         */
        public List<ComposicionPortafolioType.TipoCuenta.Estado> getEstado() {
            if (estado == null) {
                estado = new ArrayList<ComposicionPortafolioType.TipoCuenta.Estado>();
            }
            return this.estado;
        }

        /**
         * Gets the value of the tipo property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the calidadDeudor property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getCalidadDeudor() {
            return calidadDeudor;
        }

        /**
         * Sets the value of the calidadDeudor property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setCalidadDeudor(String value) {
            this.calidadDeudor = value;
        }

        /**
         * Gets the value of the porcentaje property.
         *
         * @return
         */
        public double getPorcentaje() {
            return porcentaje;
        }

        /**
         * Sets the value of the porcentaje property.
         *
         * @param value
         */
        public void setPorcentaje(double value) {
            this.porcentaje = value;
        }

        /**
         * Gets the value of the cantidad property.
         *
         * @return
         */
        public int getCantidad() {
            return cantidad;
        }

        /**
         * Sets the value of the cantidad property.
         *
         * @param value
         */
        public void setCantidad(int value) {
            this.cantidad = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Estado {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String codigo;
            @XmlAttribute(required = true)
            protected int cantidad;

            /**
             * Gets the value of the codigo property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

            /**
             * Gets the value of the cantidad property.
             *
             * @return
             */
            public int getCantidad() {
                return cantidad;
            }

            /**
             * Sets the value of the cantidad property.
             *
             * @param value
             */
            public void setCantidad(int value) {
                this.cantidad = value;
            }

        }

    }

}
