//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EntidadLocalizacionType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="EntidadLocalizacionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="codigoSuscriptor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nombreSuscriptor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nombreNit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contrato" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EntidadLocalizacionType")
public class EntidadLocalizacionType {

    @XmlAttribute
    protected String codigoSuscriptor;
    @XmlAttribute
    protected String nombreSuscriptor;
    @XmlAttribute
    protected String nit;
    @XmlAttribute
    protected String nombreNit;
    @XmlAttribute
    protected Integer contrato;

    /**
     * Gets the value of the codigoSuscriptor property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCodigoSuscriptor() {
        return codigoSuscriptor;
    }

    /**
     * Sets the value of the codigoSuscriptor property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCodigoSuscriptor(String value) {
        this.codigoSuscriptor = value;
    }

    /**
     * Gets the value of the nombreSuscriptor property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNombreSuscriptor() {
        return nombreSuscriptor;
    }

    /**
     * Sets the value of the nombreSuscriptor property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNombreSuscriptor(String value) {
        this.nombreSuscriptor = value;
    }

    /**
     * Gets the value of the nit property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNit() {
        return nit;
    }

    /**
     * Sets the value of the nit property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNit(String value) {
        this.nit = value;
    }

    /**
     * Gets the value of the nombreNit property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNombreNit() {
        return nombreNit;
    }

    /**
     * Sets the value of the nombreNit property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNombreNit(String value) {
        this.nombreNit = value;
    }

    /**
     * Gets the value of the contrato property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getContrato() {
        return contrato;
    }

    /**
     * Sets the value of the contrato property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setContrato(Integer value) {
        this.contrato = value;
    }

}
