//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for EvolucionDeudaMicrocreditoType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="EvolucionDeudaMicrocreditoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Trimestres" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Trimestre" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EvolucionDeudaSector" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="EvolucionDeudaTipoCuenta" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence minOccurs="0">
 *                             &lt;element name="EvolucionDeudaValorTrimestre" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute name="tipoCuenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="trimestre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="num" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                                     &lt;attribute name="cupoInicial" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="saldoMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="cuota" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="porcentajeDeuda" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                                     &lt;attribute name="codMenorCalificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                     &lt;attribute name="textoMenorCalificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="tipoCuenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="codSector" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="nombreSector" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EvolucionDeudaMicrocreditoType", propOrder = {
    "trimestres",
    "evolucionDeudaSector"
})
public class EvolucionDeudaMicrocreditoType {

    @XmlElement(name = "Trimestres")
    protected EvolucionDeudaMicrocreditoType.Trimestres trimestres;
    @XmlElement(name = "EvolucionDeudaSector")
    protected List<EvolucionDeudaMicrocreditoType.EvolucionDeudaSector> evolucionDeudaSector;

    /**
     * Gets the value of the trimestres property.
     *
     * @return possible object is
     *     {@link EvolucionDeudaMicrocreditoType.Trimestres }
     *
     */
    public EvolucionDeudaMicrocreditoType.Trimestres getTrimestres() {
        return trimestres;
    }

    /**
     * Sets the value of the trimestres property.
     *
     * @param value allowed object is
     *     {@link EvolucionDeudaMicrocreditoType.Trimestres }
     *
     */
    public void setTrimestres(EvolucionDeudaMicrocreditoType.Trimestres value) {
        this.trimestres = value;
    }

    /**
     * Gets the value of the evolucionDeudaSector property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the evolucionDeudaSector property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvolucionDeudaSector().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EvolucionDeudaMicrocreditoType.EvolucionDeudaSector }
     *
     *
     * @return 
     */
    public List<EvolucionDeudaMicrocreditoType.EvolucionDeudaSector> getEvolucionDeudaSector() {
        if (evolucionDeudaSector == null) {
            evolucionDeudaSector = new ArrayList<EvolucionDeudaMicrocreditoType.EvolucionDeudaSector>();
        }
        return this.evolucionDeudaSector;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="EvolucionDeudaTipoCuenta" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence minOccurs="0">
     *                   &lt;element name="EvolucionDeudaValorTrimestre" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute name="tipoCuenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="trimestre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="num" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                           &lt;attribute name="cupoInicial" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="saldoMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="cuota" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="porcentajeDeuda" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                           &lt;attribute name="codMenorCalificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                           &lt;attribute name="textoMenorCalificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="tipoCuenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="codSector" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="nombreSector" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "evolucionDeudaTipoCuenta"
    })
    public static class EvolucionDeudaSector {

        @XmlElement(name = "EvolucionDeudaTipoCuenta")
        protected List<EvolucionDeudaMicrocreditoType.EvolucionDeudaSector.EvolucionDeudaTipoCuenta> evolucionDeudaTipoCuenta;
        @XmlAttribute(required = true)
        protected int codSector;
        @XmlAttribute(required = true)
        protected String nombreSector;

        /**
         * Gets the value of the evolucionDeudaTipoCuenta property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the evolucionDeudaTipoCuenta property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvolucionDeudaTipoCuenta().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EvolucionDeudaMicrocreditoType.EvolucionDeudaSector.EvolucionDeudaTipoCuenta }
         *
         *
         * @return 
         */
        public List<EvolucionDeudaMicrocreditoType.EvolucionDeudaSector.EvolucionDeudaTipoCuenta> getEvolucionDeudaTipoCuenta() {
            if (evolucionDeudaTipoCuenta == null) {
                evolucionDeudaTipoCuenta = new ArrayList<EvolucionDeudaMicrocreditoType.EvolucionDeudaSector.EvolucionDeudaTipoCuenta>();
            }
            return this.evolucionDeudaTipoCuenta;
        }

        /**
         * Gets the value of the codSector property.
         *
         * @return 
         */
        public int getCodSector() {
            return codSector;
        }

        /**
         * Sets the value of the codSector property.
         *
         * @param value
         */
        public void setCodSector(int value) {
            this.codSector = value;
        }

        /**
         * Gets the value of the nombreSector property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNombreSector() {
            return nombreSector;
        }

        /**
         * Sets the value of the nombreSector property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNombreSector(String value) {
            this.nombreSector = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence minOccurs="0">
         *         &lt;element name="EvolucionDeudaValorTrimestre" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute name="tipoCuenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="trimestre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="num" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *                 &lt;attribute name="cupoInicial" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="saldoMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="cuota" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="porcentajeDeuda" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *                 &lt;attribute name="codMenorCalificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *                 &lt;attribute name="textoMenorCalificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="tipoCuenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "evolucionDeudaValorTrimestre"
        })
        public static class EvolucionDeudaTipoCuenta {

            @XmlElement(name = "EvolucionDeudaValorTrimestre")
            protected List<EvolucionDeudaMicrocreditoType.EvolucionDeudaSector.EvolucionDeudaTipoCuenta.EvolucionDeudaValorTrimestre> evolucionDeudaValorTrimestre;
            @XmlAttribute(required = true)
            protected String tipoCuenta;

            /**
             * Gets the value of the evolucionDeudaValorTrimestre property.
             *
             * <p>
             * This accessor method returns a reference to the live list, not a
             * snapshot. Therefore any modification you make to the returned
             * list will be present inside the JAXB object. This is why there is
             * not a <CODE>set</CODE> method for the
             * evolucionDeudaValorTrimestre property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEvolucionDeudaValorTrimestre().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link EvolucionDeudaMicrocreditoType.EvolucionDeudaSector.EvolucionDeudaTipoCuenta.EvolucionDeudaValorTrimestre }
             *
             *
             * @return 
             */
            public List<EvolucionDeudaMicrocreditoType.EvolucionDeudaSector.EvolucionDeudaTipoCuenta.EvolucionDeudaValorTrimestre> getEvolucionDeudaValorTrimestre() {
                if (evolucionDeudaValorTrimestre == null) {
                    evolucionDeudaValorTrimestre = new ArrayList<EvolucionDeudaMicrocreditoType.EvolucionDeudaSector.EvolucionDeudaTipoCuenta.EvolucionDeudaValorTrimestre>();
                }
                return this.evolucionDeudaValorTrimestre;
            }

            /**
             * Gets the value of the tipoCuenta property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getTipoCuenta() {
                return tipoCuenta;
            }

            /**
             * Sets the value of the tipoCuenta property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setTipoCuenta(String value) {
                this.tipoCuenta = value;
            }

            /**
             * <p>
             * Java class for anonymous complex type.
             *
             * <p>
             * The following schema fragment specifies the expected content
             * contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute name="tipoCuenta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="trimestre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="num" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
             *       &lt;attribute name="cupoInicial" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="saldoMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="cuota" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="porcentajeDeuda" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
             *       &lt;attribute name="codMenorCalificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *       &lt;attribute name="textoMenorCalificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class EvolucionDeudaValorTrimestre {

                @XmlAttribute(required = true)
                protected String tipoCuenta;
                @XmlAttribute(required = true)
                protected String trimestre;
                @XmlAttribute(required = true)
                protected int num;
                @XmlAttribute(required = true)
                protected double cupoInicial;
                @XmlAttribute(required = true)
                protected double saldo;
                @XmlAttribute(required = true)
                protected double saldoMora;
                @XmlAttribute(required = true)
                protected double cuota;
                @XmlAttribute(required = true)
                protected double porcentajeDeuda;
                @XmlAttribute(required = true)
                protected String codMenorCalificacion;
                @XmlAttribute(required = true)
                protected String textoMenorCalificacion;

                /**
                 * Gets the value of the tipoCuenta property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getTipoCuenta() {
                    return tipoCuenta;
                }

                /**
                 * Sets the value of the tipoCuenta property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setTipoCuenta(String value) {
                    this.tipoCuenta = value;
                }

                /**
                 * Gets the value of the trimestre property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getTrimestre() {
                    return trimestre;
                }

                /**
                 * Sets the value of the trimestre property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setTrimestre(String value) {
                    this.trimestre = value;
                }

                /**
                 * Gets the value of the num property.
                 *
                 * @return 
                 */
                public int getNum() {
                    return num;
                }

                /**
                 * Sets the value of the num property.
                 *
                 * @param value
                 */
                public void setNum(int value) {
                    this.num = value;
                }

                /**
                 * Gets the value of the cupoInicial property.
                 *
                 * @return 
                 */
                public double getCupoInicial() {
                    return cupoInicial;
                }

                /**
                 * Sets the value of the cupoInicial property.
                 *
                 * @param value
                 */
                public void setCupoInicial(double value) {
                    this.cupoInicial = value;
                }

                /**
                 * Gets the value of the saldo property.
                 *
                 * @return 
                 */
                public double getSaldo() {
                    return saldo;
                }

                /**
                 * Sets the value of the saldo property.
                 *
                 * @param value
                 */
                public void setSaldo(double value) {
                    this.saldo = value;
                }

                /**
                 * Gets the value of the saldoMora property.
                 *
                 * @return 
                 */
                public double getSaldoMora() {
                    return saldoMora;
                }

                /**
                 * Sets the value of the saldoMora property.
                 *
                 * @param value
                 */
                public void setSaldoMora(double value) {
                    this.saldoMora = value;
                }

                /**
                 * Gets the value of the cuota property.
                 *
                 * @return 
                 */
                public double getCuota() {
                    return cuota;
                }

                /**
                 * Sets the value of the cuota property.
                 *
                 * @param value
                 */
                public void setCuota(double value) {
                    this.cuota = value;
                }

                /**
                 * Gets the value of the porcentajeDeuda property.
                 *
                 * @return 
                 */
                public double getPorcentajeDeuda() {
                    return porcentajeDeuda;
                }

                /**
                 * Sets the value of the porcentajeDeuda property.
                 *
                 * @param value
                 */
                public void setPorcentajeDeuda(double value) {
                    this.porcentajeDeuda = value;
                }

                /**
                 * Gets the value of the codMenorCalificacion property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getCodMenorCalificacion() {
                    return codMenorCalificacion;
                }

                /**
                 * Sets the value of the codMenorCalificacion property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setCodMenorCalificacion(String value) {
                    this.codMenorCalificacion = value;
                }

                /**
                 * Gets the value of the textoMenorCalificacion property.
                 *
                 * @return possible object is {@link String }
                 *
                 */
                public String getTextoMenorCalificacion() {
                    return textoMenorCalificacion;
                }

                /**
                 * Sets the value of the textoMenorCalificacion property.
                 *
                 * @param value allowed object is {@link String }
                 *
                 */
                public void setTextoMenorCalificacion(String value) {
                    this.textoMenorCalificacion = value;
                }

            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Trimestre" type="{http://www.w3.org/2001/XMLSchema}anyType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trimestre"
    })
    public static class Trimestres {

        //@XmlElement(name = "Trimestre")
        @XmlAnyElement(lax = true)
        protected List<Object> trimestre;

        /**
         * Gets the value of the trimestre property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the trimestre property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTrimestre().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         *
         *
         * @return 
         */
        public List<Object> getTrimestre() {
            if (trimestre == null) {
                trimestre = new ArrayList<Object>();
            }
            return this.trimestre;
        }

    }

}
