//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for HistoricoSaldosType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="HistoricoSaldosType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="TipoCuenta" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="Trimestre" maxOccurs="8">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="totalCuentas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="cuentasConsideradas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Totales" maxOccurs="8" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="totalCuentas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="cuentasConsideradas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoricoSaldosType", propOrder = {
    "tipoCuenta",
    "totales"
})
public class HistoricoSaldosType {

    @XmlElement(name = "TipoCuenta")
    protected List<HistoricoSaldosType.TipoCuenta> tipoCuenta;
    @XmlElement(name = "Totales")
    protected List<HistoricoSaldosType.Totales> totales;

    /**
     * Gets the value of the tipoCuenta property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the tipoCuenta property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipoCuenta().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HistoricoSaldosType.TipoCuenta }
     *
     *
     * @return 
     */
    public List<HistoricoSaldosType.TipoCuenta> getTipoCuenta() {
        if (tipoCuenta == null) {
            tipoCuenta = new ArrayList<HistoricoSaldosType.TipoCuenta>();
        }
        return this.tipoCuenta;
    }

    /**
     * Gets the value of the totales property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the totales property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTotales().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HistoricoSaldosType.Totales }
     *
     *
     * @return 
     */
    public List<HistoricoSaldosType.Totales> getTotales() {
        if (totales == null) {
            totales = new ArrayList<HistoricoSaldosType.Totales>();
        }
        return this.totales;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="Trimestre" maxOccurs="8">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="totalCuentas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="cuentasConsideradas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trimestre"
    })
    public static class TipoCuenta {

        @XmlElement(name = "Trimestre")
        protected List<HistoricoSaldosType.TipoCuenta.Trimestre> trimestre;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anySimpleType")
        protected String tipo;

        /**
         * Gets the value of the trimestre property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the trimestre property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTrimestre().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HistoricoSaldosType.TipoCuenta.Trimestre }
         *
         *
         * @return 
         */
        public List<HistoricoSaldosType.TipoCuenta.Trimestre> getTrimestre() {
            if (trimestre == null) {
                trimestre = new ArrayList<HistoricoSaldosType.TipoCuenta.Trimestre>();
            }
            return this.trimestre;
        }

        /**
         * Gets the value of the tipo property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="totalCuentas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="cuentasConsideradas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Trimestre {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fecha;
            @XmlAttribute(required = true)
            protected int totalCuentas;
            @XmlAttribute(required = true)
            protected int cuentasConsideradas;
            @XmlAttribute(required = true)
            protected double saldo;

            /**
             * Gets the value of the fecha property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

            /**
             * Gets the value of the totalCuentas property.
             *
             * @return 
             */
            public int getTotalCuentas() {
                return totalCuentas;
            }

            /**
             * Sets the value of the totalCuentas property.
             *
             * @param value
             */
            public void setTotalCuentas(int value) {
                this.totalCuentas = value;
            }

            /**
             * Gets the value of the cuentasConsideradas property.
             *
             * @return 
             */
            public int getCuentasConsideradas() {
                return cuentasConsideradas;
            }

            /**
             * Sets the value of the cuentasConsideradas property.
             *
             * @param value
             */
            public void setCuentasConsideradas(int value) {
                this.cuentasConsideradas = value;
            }

            /**
             * Gets the value of the saldo property.
             *
             * @return 
             */
            public double getSaldo() {
                return saldo;
            }

            /**
             * Sets the value of the saldo property.
             *
             * @param value
             */
            public void setSaldo(double value) {
                this.saldo = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="totalCuentas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="cuentasConsideradas" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Totales {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;
        @XmlAttribute(required = true)
        protected int totalCuentas;
        @XmlAttribute(required = true)
        protected int cuentasConsideradas;
        @XmlAttribute(required = true)
        protected double saldo;

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

        /**
         * Gets the value of the totalCuentas property.
         *
         * @return 
         */
        public int getTotalCuentas() {
            return totalCuentas;
        }

        /**
         * Sets the value of the totalCuentas property.
         *
         * @param value
         */
        public void setTotalCuentas(int value) {
            this.totalCuentas = value;
        }

        /**
         * Gets the value of the cuentasConsideradas property.
         *
         * @return 
         */
        public int getCuentasConsideradas() {
            return cuentasConsideradas;
        }

        /**
         * Sets the value of the cuentasConsideradas property.
         *
         * @param value
         */
        public void setCuentasConsideradas(int value) {
            this.cuentasConsideradas = value;
        }

        /**
         * Gets the value of the saldo property.
         *
         * @return 
         */
        public double getSaldo() {
            return saldo;
        }

        /**
         * Sets the value of the saldo property.
         *
         * @param value
         */
        public void setSaldo(double value) {
            this.saldo = value;
        }

    }

}
