//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for InfoAgregadaMicrocreditoType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="InfoAgregadaMicrocreditoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Resumen" type="{}ResumenMicrocreditoType" minOccurs="0"/>
 *         &lt;element name="ComportamientoEntidades" type="{}ComportamientoEntidadesType" minOccurs="0"/>
 *         &lt;element name="AnalisisVectores" type="{}AnalisisVectoresType" minOccurs="0"/>
 *         &lt;element name="EvolucionDeuda" type="{}EvolucionDeudaMicrocreditoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoAgregadaMicrocreditoType", propOrder = {
    "resumen",
    "comportamientoEntidades",
    "analisisVectores",
    "evolucionDeuda"
})
public class InfoAgregadaMicrocreditoType {

    @XmlElement(name = "Resumen")
    protected ResumenMicrocreditoType resumen;
    @XmlElement(name = "ComportamientoEntidades")
    protected ComportamientoEntidadesType comportamientoEntidades;
    @XmlElement(name = "AnalisisVectores")
    protected AnalisisVectoresType analisisVectores;
    @XmlElement(name = "EvolucionDeuda")
    protected EvolucionDeudaMicrocreditoType evolucionDeuda;

    /**
     * Gets the value of the resumen property.
     *
     * @return possible object is {@link ResumenMicrocreditoType }
     *
     */
    public ResumenMicrocreditoType getResumen() {
        return resumen;
    }

    /**
     * Sets the value of the resumen property.
     *
     * @param value allowed object is {@link ResumenMicrocreditoType }
     *
     */
    public void setResumen(ResumenMicrocreditoType value) {
        this.resumen = value;
    }

    /**
     * Gets the value of the comportamientoEntidades property.
     *
     * @return possible object is {@link ComportamientoEntidadesType }
     *
     */
    public ComportamientoEntidadesType getComportamientoEntidades() {
        return comportamientoEntidades;
    }

    /**
     * Sets the value of the comportamientoEntidades property.
     *
     * @param value allowed object is {@link ComportamientoEntidadesType }
     *
     */
    public void setComportamientoEntidades(ComportamientoEntidadesType value) {
        this.comportamientoEntidades = value;
    }

    /**
     * Gets the value of the analisisVectores property.
     *
     * @return possible object is {@link AnalisisVectoresType }
     *
     */
    public AnalisisVectoresType getAnalisisVectores() {
        return analisisVectores;
    }

    /**
     * Sets the value of the analisisVectores property.
     *
     * @param value allowed object is {@link AnalisisVectoresType }
     *
     */
    public void setAnalisisVectores(AnalisisVectoresType value) {
        this.analisisVectores = value;
    }

    /**
     * Gets the value of the evolucionDeuda property.
     *
     * @return possible object is {@link EvolucionDeudaMicrocreditoType }
     *
     */
    public EvolucionDeudaMicrocreditoType getEvolucionDeuda() {
        return evolucionDeuda;
    }

    /**
     * Sets the value of the evolucionDeuda property.
     *
     * @param value allowed object is {@link EvolucionDeudaMicrocreditoType }
     *
     */
    public void setEvolucionDeuda(EvolucionDeudaMicrocreditoType value) {
        this.evolucionDeuda = value;
    }

}
