//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for InfoDemograficaType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="InfoDemograficaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Empleador" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nombre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tipoContrato" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fechaIngreso" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ActividadEconomica" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="CIIU" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="estrato" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="estado" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nitReporta" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PersonasACargo" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EstadoCivil" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NivelEstudios" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nivel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EstadoFinanciero" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="pasivos" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="activos" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="ingresos" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="OperacionesInternacionales" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="operaInt" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Identificacion" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fechaExpedicion" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="lugarExpedicion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fechaNacimiento" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fecha" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="FuerzaMayor" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fuerzaMayor" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fechaFuerzaMayor" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoDemograficaType", propOrder = {
    "empleador",
    "actividadEconomica",
    "personasACargo",
    "estadoCivil",
    "nivelEstudios",
    "estadoFinanciero",
    "operacionesInternacionales",
    "identificacion",
    "fuerzaMayor"
})
@XmlSeeAlso({
    com.jamar.historiacreditowss.jamarhistoriadecredito.generics.NaturalExtranjeraType.InfoDemografica.class,
    com.jamar.historiacreditowss.jamarhistoriadecredito.generics.NaturalNacionalType.InfoDemografica.class
})
public class InfoDemograficaType {

    @XmlElement(name = "Empleador")
    protected List<InfoDemograficaType.Empleador> empleador;
    @XmlElement(name = "ActividadEconomica")
    protected List<InfoDemograficaType.ActividadEconomica> actividadEconomica;
    @XmlElement(name = "PersonasACargo")
    protected List<InfoDemograficaType.PersonasACargo> personasACargo;
    @XmlElement(name = "EstadoCivil")
    protected List<InfoDemograficaType.EstadoCivil> estadoCivil;
    @XmlElement(name = "NivelEstudios")
    protected List<InfoDemograficaType.NivelEstudios> nivelEstudios;
    @XmlElement(name = "EstadoFinanciero")
    protected List<InfoDemograficaType.EstadoFinanciero> estadoFinanciero;
    @XmlElement(name = "OperacionesInternacionales")
    protected List<InfoDemograficaType.OperacionesInternacionales> operacionesInternacionales;
    @XmlElement(name = "Identificacion")
    protected List<InfoDemograficaType.Identificacion> identificacion;
    @XmlElement(name = "FuerzaMayor")
    protected List<InfoDemograficaType.FuerzaMayor> fuerzaMayor;

    /**
     * Gets the value of the empleador property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the empleador property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEmpleador().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InfoDemograficaType.Empleador }
     *
     *
     * @return 
     */
    public List<InfoDemograficaType.Empleador> getEmpleador() {
        if (empleador == null) {
            empleador = new ArrayList<InfoDemograficaType.Empleador>();
        }
        return this.empleador;
    }

    /**
     * Gets the value of the actividadEconomica property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the actividadEconomica property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActividadEconomica().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InfoDemograficaType.ActividadEconomica }
     *
     *
     * @return 
     */
    public List<InfoDemograficaType.ActividadEconomica> getActividadEconomica() {
        if (actividadEconomica == null) {
            actividadEconomica = new ArrayList<InfoDemograficaType.ActividadEconomica>();
        }
        return this.actividadEconomica;
    }

    /**
     * Gets the value of the personasACargo property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the personasACargo property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonasACargo().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InfoDemograficaType.PersonasACargo }
     *
     *
     * @return 
     */
    public List<InfoDemograficaType.PersonasACargo> getPersonasACargo() {
        if (personasACargo == null) {
            personasACargo = new ArrayList<InfoDemograficaType.PersonasACargo>();
        }
        return this.personasACargo;
    }

    /**
     * Gets the value of the estadoCivil property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the estadoCivil property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstadoCivil().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InfoDemograficaType.EstadoCivil }
     *
     *
     * @return 
     */
    public List<InfoDemograficaType.EstadoCivil> getEstadoCivil() {
        if (estadoCivil == null) {
            estadoCivil = new ArrayList<InfoDemograficaType.EstadoCivil>();
        }
        return this.estadoCivil;
    }

    /**
     * Gets the value of the nivelEstudios property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the nivelEstudios property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNivelEstudios().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InfoDemograficaType.NivelEstudios }
     *
     *
     * @return 
     */
    public List<InfoDemograficaType.NivelEstudios> getNivelEstudios() {
        if (nivelEstudios == null) {
            nivelEstudios = new ArrayList<InfoDemograficaType.NivelEstudios>();
        }
        return this.nivelEstudios;
    }

    /**
     * Gets the value of the estadoFinanciero property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the estadoFinanciero property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEstadoFinanciero().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InfoDemograficaType.EstadoFinanciero }
     *
     *
     * @return 
     */
    public List<InfoDemograficaType.EstadoFinanciero> getEstadoFinanciero() {
        if (estadoFinanciero == null) {
            estadoFinanciero = new ArrayList<InfoDemograficaType.EstadoFinanciero>();
        }
        return this.estadoFinanciero;
    }

    /**
     * Gets the value of the operacionesInternacionales property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the operacionesInternacionales property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperacionesInternacionales().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InfoDemograficaType.OperacionesInternacionales }
     *
     *
     * @return 
     */
    public List<InfoDemograficaType.OperacionesInternacionales> getOperacionesInternacionales() {
        if (operacionesInternacionales == null) {
            operacionesInternacionales = new ArrayList<InfoDemograficaType.OperacionesInternacionales>();
        }
        return this.operacionesInternacionales;
    }

    /**
     * Gets the value of the identificacion property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the identificacion property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentificacion().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InfoDemograficaType.Identificacion }
     *
     *
     * @return 
     */
    public List<InfoDemograficaType.Identificacion> getIdentificacion() {
        if (identificacion == null) {
            identificacion = new ArrayList<InfoDemograficaType.Identificacion>();
        }
        return this.identificacion;
    }

    /**
     * Gets the value of the fuerzaMayor property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the fuerzaMayor property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFuerzaMayor().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InfoDemograficaType.FuerzaMayor }
     *
     *
     * @return 
     */
    public List<InfoDemograficaType.FuerzaMayor> getFuerzaMayor() {
        if (fuerzaMayor == null) {
            fuerzaMayor = new ArrayList<InfoDemograficaType.FuerzaMayor>();
        }
        return this.fuerzaMayor;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="CIIU" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="estrato" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="estado" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nitReporta" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ActividadEconomica {

        @XmlAttribute
        protected String idRegistro;
        @XmlAttribute(required = true)
        protected String tipo;
        @XmlAttribute(name = "CIIU")
        protected String ciiu;
        @XmlAttribute
        protected Integer estrato;
        @XmlAttribute
        protected String estado;
        @XmlAttribute
        protected String nitReporta;
        @XmlAttribute
        protected String razonSocial;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;

        /**
         * Gets the value of the idRegistro property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getIdRegistro() {
            return idRegistro;
        }

        /**
         * Sets the value of the idRegistro property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setIdRegistro(String value) {
            this.idRegistro = value;
        }

        /**
         * Gets the value of the tipo property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

        /**
         * Gets the value of the ciiu property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getCIIU() {
            return ciiu;
        }

        /**
         * Sets the value of the ciiu property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setCIIU(String value) {
            this.ciiu = value;
        }

        /**
         * Gets the value of the estrato property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getEstrato() {
            return estrato;
        }

        /**
         * Sets the value of the estrato property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setEstrato(Integer value) {
            this.estrato = value;
        }

        /**
         * Gets the value of the estado property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setEstado(String value) {
            this.estado = value;
        }

        /**
         * Gets the value of the nitReporta property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNitReporta() {
            return nitReporta;
        }

        /**
         * Sets the value of the nitReporta property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNitReporta(String value) {
            this.nitReporta = value;
        }

        /**
         * Gets the value of the razonSocial property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRazonSocial() {
            return razonSocial;
        }

        /**
         * Sets the value of the razonSocial property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRazonSocial(String value) {
            this.razonSocial = value;
        }

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nombre" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="tipoContrato" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fechaIngreso" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Empleador {

        @XmlAttribute
        protected String idRegistro;
        @XmlAttribute(required = true)
        protected String nombre;
        @XmlAttribute
        protected String nit;
        @XmlAttribute
        protected String tipoContrato;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaIngreso;
        @XmlAttribute(required = true)
        protected String nitReporta;
        @XmlAttribute
        protected String razonSocial;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;

        /**
         * Gets the value of the idRegistro property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getIdRegistro() {
            return idRegistro;
        }

        /**
         * Sets the value of the idRegistro property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setIdRegistro(String value) {
            this.idRegistro = value;
        }

        /**
         * Gets the value of the nombre property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNombre() {
            return nombre;
        }

        /**
         * Sets the value of the nombre property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNombre(String value) {
            this.nombre = value;
        }

        /**
         * Gets the value of the nit property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNit() {
            return nit;
        }

        /**
         * Sets the value of the nit property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNit(String value) {
            this.nit = value;
        }

        /**
         * Gets the value of the tipoContrato property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getTipoContrato() {
            return tipoContrato;
        }

        /**
         * Sets the value of the tipoContrato property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setTipoContrato(String value) {
            this.tipoContrato = value;
        }

        /**
         * Gets the value of the fechaIngreso property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFechaIngreso() {
            return fechaIngreso;
        }

        /**
         * Sets the value of the fechaIngreso property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFechaIngreso(XMLGregorianCalendar value) {
            this.fechaIngreso = value;
        }

        /**
         * Gets the value of the nitReporta property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNitReporta() {
            return nitReporta;
        }

        /**
         * Sets the value of the nitReporta property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNitReporta(String value) {
            this.nitReporta = value;
        }

        /**
         * Gets the value of the razonSocial property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRazonSocial() {
            return razonSocial;
        }

        /**
         * Sets the value of the razonSocial property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRazonSocial(String value) {
            this.razonSocial = value;
        }

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="estado" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EstadoCivil {

        @XmlAttribute
        protected String idRegistro;
        @XmlAttribute(required = true)
        protected String estado;
        @XmlAttribute(required = true)
        protected String nitReporta;
        @XmlAttribute
        protected String razonSocial;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;

        /**
         * Gets the value of the idRegistro property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getIdRegistro() {
            return idRegistro;
        }

        /**
         * Sets the value of the idRegistro property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setIdRegistro(String value) {
            this.idRegistro = value;
        }

        /**
         * Gets the value of the estado property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setEstado(String value) {
            this.estado = value;
        }

        /**
         * Gets the value of the nitReporta property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNitReporta() {
            return nitReporta;
        }

        /**
         * Sets the value of the nitReporta property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNitReporta(String value) {
            this.nitReporta = value;
        }

        /**
         * Gets the value of the razonSocial property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRazonSocial() {
            return razonSocial;
        }

        /**
         * Sets the value of the razonSocial property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRazonSocial(String value) {
            this.razonSocial = value;
        }

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="pasivos" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="activos" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="ingresos" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class EstadoFinanciero {

        @XmlAttribute
        protected String idRegistro;
        @XmlAttribute
        protected Double pasivos;
        @XmlAttribute
        protected Double activos;
        @XmlAttribute
        protected Double ingresos;
        @XmlAttribute(required = true)
        protected String nitReporta;
        @XmlAttribute
        protected String razonSocial;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;

        /**
         * Gets the value of the idRegistro property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getIdRegistro() {
            return idRegistro;
        }

        /**
         * Sets the value of the idRegistro property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setIdRegistro(String value) {
            this.idRegistro = value;
        }

        /**
         * Gets the value of the pasivos property.
         *
         * @return possible object is {@link Double }
         *
         */
        public Double getPasivos() {
            return pasivos;
        }

        /**
         * Sets the value of the pasivos property.
         *
         * @param value allowed object is {@link Double }
         *
         */
        public void setPasivos(Double value) {
            this.pasivos = value;
        }

        /**
         * Gets the value of the activos property.
         *
         * @return possible object is {@link Double }
         *
         */
        public Double getActivos() {
            return activos;
        }

        /**
         * Sets the value of the activos property.
         *
         * @param value allowed object is {@link Double }
         *
         */
        public void setActivos(Double value) {
            this.activos = value;
        }

        /**
         * Gets the value of the ingresos property.
         *
         * @return possible object is {@link Double }
         *
         */
        public Double getIngresos() {
            return ingresos;
        }

        /**
         * Sets the value of the ingresos property.
         *
         * @param value allowed object is {@link Double }
         *
         */
        public void setIngresos(Double value) {
            this.ingresos = value;
        }

        /**
         * Gets the value of the nitReporta property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNitReporta() {
            return nitReporta;
        }

        /**
         * Sets the value of the nitReporta property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNitReporta(String value) {
            this.nitReporta = value;
        }

        /**
         * Gets the value of the razonSocial property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRazonSocial() {
            return razonSocial;
        }

        /**
         * Sets the value of the razonSocial property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRazonSocial(String value) {
            this.razonSocial = value;
        }

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fuerzaMayor" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fechaFuerzaMayor" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class FuerzaMayor {

        @XmlAttribute
        protected String idRegistro;
        @XmlAttribute(required = true)
        protected boolean fuerzaMayor;
        @XmlAttribute(required = true)
        protected String nitReporta;
        @XmlAttribute
        protected String razonSocial;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaFuerzaMayor;

        /**
         * Gets the value of the idRegistro property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getIdRegistro() {
            return idRegistro;
        }

        /**
         * Sets the value of the idRegistro property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setIdRegistro(String value) {
            this.idRegistro = value;
        }

        /**
         * Gets the value of the fuerzaMayor property.
         *
         * @return 
         */
        public boolean isFuerzaMayor() {
            return fuerzaMayor;
        }

        /**
         * Sets the value of the fuerzaMayor property.
         *
         * @param value
         */
        public void setFuerzaMayor(boolean value) {
            this.fuerzaMayor = value;
        }

        /**
         * Gets the value of the nitReporta property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNitReporta() {
            return nitReporta;
        }

        /**
         * Sets the value of the nitReporta property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNitReporta(String value) {
            this.nitReporta = value;
        }

        /**
         * Gets the value of the razonSocial property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRazonSocial() {
            return razonSocial;
        }

        /**
         * Sets the value of the razonSocial property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRazonSocial(String value) {
            this.razonSocial = value;
        }

        /**
         * Gets the value of the fechaFuerzaMayor property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFechaFuerzaMayor() {
            return fechaFuerzaMayor;
        }

        /**
         * Sets the value of the fechaFuerzaMayor property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFechaFuerzaMayor(XMLGregorianCalendar value) {
            this.fechaFuerzaMayor = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fechaExpedicion" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="lugarExpedicion" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fechaNacimiento" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fecha" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Identificacion {

        @XmlAttribute
        protected String idRegistro;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaExpedicion;
        @XmlAttribute
        protected String lugarExpedicion;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaNacimiento;
        @XmlAttribute(required = true)
        protected String nitReporta;
        @XmlAttribute
        protected String razonSocial;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;

        /**
         * Gets the value of the idRegistro property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getIdRegistro() {
            return idRegistro;
        }

        /**
         * Sets the value of the idRegistro property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setIdRegistro(String value) {
            this.idRegistro = value;
        }

        /**
         * Gets the value of the fechaExpedicion property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFechaExpedicion() {
            return fechaExpedicion;
        }

        /**
         * Sets the value of the fechaExpedicion property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFechaExpedicion(XMLGregorianCalendar value) {
            this.fechaExpedicion = value;
        }

        /**
         * Gets the value of the lugarExpedicion property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getLugarExpedicion() {
            return lugarExpedicion;
        }

        /**
         * Sets the value of the lugarExpedicion property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setLugarExpedicion(String value) {
            this.lugarExpedicion = value;
        }

        /**
         * Gets the value of the fechaNacimiento property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFechaNacimiento() {
            return fechaNacimiento;
        }

        /**
         * Sets the value of the fechaNacimiento property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFechaNacimiento(XMLGregorianCalendar value) {
            this.fechaNacimiento = value;
        }

        /**
         * Gets the value of the nitReporta property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNitReporta() {
            return nitReporta;
        }

        /**
         * Sets the value of the nitReporta property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNitReporta(String value) {
            this.nitReporta = value;
        }

        /**
         * Gets the value of the razonSocial property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRazonSocial() {
            return razonSocial;
        }

        /**
         * Sets the value of the razonSocial property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRazonSocial(String value) {
            this.razonSocial = value;
        }

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nivel" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class NivelEstudios {

        @XmlAttribute
        protected String idRegistro;
        @XmlAttribute(required = true)
        protected String nivel;
        @XmlAttribute(required = true)
        protected String nitReporta;
        @XmlAttribute
        protected String razonSocial;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;

        /**
         * Gets the value of the idRegistro property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getIdRegistro() {
            return idRegistro;
        }

        /**
         * Sets the value of the idRegistro property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setIdRegistro(String value) {
            this.idRegistro = value;
        }

        /**
         * Gets the value of the nivel property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNivel() {
            return nivel;
        }

        /**
         * Sets the value of the nivel property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNivel(String value) {
            this.nivel = value;
        }

        /**
         * Gets the value of the nitReporta property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNitReporta() {
            return nitReporta;
        }

        /**
         * Sets the value of the nitReporta property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNitReporta(String value) {
            this.nitReporta = value;
        }

        /**
         * Gets the value of the razonSocial property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRazonSocial() {
            return razonSocial;
        }

        /**
         * Sets the value of the razonSocial property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRazonSocial(String value) {
            this.razonSocial = value;
        }

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="operaInt" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class OperacionesInternacionales {

        @XmlAttribute(required = true)
        protected boolean operaInt;
        @XmlAttribute(required = true)
        protected String nitReporta;
        @XmlAttribute
        protected String razonSocial;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;
        @XmlAttribute
        protected String idRegistro;

        /**
         * Gets the value of the operaInt property.
         *
         * @return 
         */
        public boolean isOperaInt() {
            return operaInt;
        }

        /**
         * Sets the value of the operaInt property.
         *
         * @param value
         */
        public void setOperaInt(boolean value) {
            this.operaInt = value;
        }

        /**
         * Gets the value of the nitReporta property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNitReporta() {
            return nitReporta;
        }

        /**
         * Sets the value of the nitReporta property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNitReporta(String value) {
            this.nitReporta = value;
        }

        /**
         * Gets the value of the razonSocial property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRazonSocial() {
            return razonSocial;
        }

        /**
         * Sets the value of the razonSocial property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRazonSocial(String value) {
            this.razonSocial = value;
        }

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

        /**
         * Gets the value of the idRegistro property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getIdRegistro() {
            return idRegistro;
        }

        /**
         * Sets the value of the idRegistro property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setIdRegistro(String value) {
            this.idRegistro = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="idRegistro" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="nitReporta" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="razonSocial" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class PersonasACargo {

        @XmlAttribute
        protected String idRegistro;
        @XmlAttribute(required = true)
        protected short cantidad;
        @XmlAttribute(required = true)
        protected String nitReporta;
        @XmlAttribute
        protected String razonSocial;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fecha;

        /**
         * Gets the value of the idRegistro property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getIdRegistro() {
            return idRegistro;
        }

        /**
         * Sets the value of the idRegistro property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setIdRegistro(String value) {
            this.idRegistro = value;
        }

        /**
         * Gets the value of the cantidad property.
         *
         * @return 
         */
        public short getCantidad() {
            return cantidad;
        }

        /**
         * Sets the value of the cantidad property.
         *
         * @param value
         */
        public void setCantidad(short value) {
            this.cantidad = value;
        }

        /**
         * Gets the value of the nitReporta property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNitReporta() {
            return nitReporta;
        }

        /**
         * Sets the value of the nitReporta property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNitReporta(String value) {
            this.nitReporta = value;
        }

        /**
         * Gets the value of the razonSocial property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getRazonSocial() {
            return razonSocial;
        }

        /**
         * Sets the value of the razonSocial property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setRazonSocial(String value) {
            this.razonSocial = value;
        }

        /**
         * Gets the value of the fecha property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFecha() {
            return fecha;
        }

        /**
         * Sets the value of the fecha property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFecha(XMLGregorianCalendar value) {
            this.fecha = value;
        }

    }

}
