//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for InfoAgregadaType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="InfoAgregadaType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Resumen" type="{}ResumenType" minOccurs="0"/>
 *         &lt;element name="Totales" type="{}TotalesType" minOccurs="0"/>
 *         &lt;element name="ComposicionPortafolio" type="{}ComposicionPortafolioType" minOccurs="0"/>
 *         &lt;element name="Cheques" type="{}ChequesType" minOccurs="0"/>
 *         &lt;element name="EvolucionDeuda" type="{}EvolucionDeudaType" minOccurs="0"/>
 *         &lt;element name="HistoricoSaldos" type="{}HistoricoSaldosType" minOccurs="0"/>
 *         &lt;element name="ResumenEndeudamiento" type="{}ResumenEndeudamientoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfoAgregadaType", propOrder = {
    "resumen",
    "totales",
    "composicionPortafolio",
    "cheques",
    "evolucionDeuda",
    "historicoSaldos",
    "resumenEndeudamiento"
})
public class InfoAgregadaType {

    @XmlElement(name = "Resumen")
    protected ResumenType resumen;
    @XmlElement(name = "Totales")
    protected TotalesType totales;
    @XmlElement(name = "ComposicionPortafolio")
    protected ComposicionPortafolioType composicionPortafolio;
    @XmlElement(name = "Cheques")
    protected ChequesType cheques;
    @XmlElement(name = "EvolucionDeuda")
    protected EvolucionDeudaType evolucionDeuda;
    @XmlElement(name = "HistoricoSaldos")
    protected HistoricoSaldosType historicoSaldos;
    @XmlElement(name = "ResumenEndeudamiento")
    protected ResumenEndeudamientoType resumenEndeudamiento;

    /**
     * Gets the value of the resumen property.
     *
     * @return possible object is {@link ResumenType }
     *
     */
    public ResumenType getResumen() {
        return resumen;
    }

    /**
     * Sets the value of the resumen property.
     *
     * @param value allowed object is {@link ResumenType }
     *
     */
    public void setResumen(ResumenType value) {
        this.resumen = value;
    }

    /**
     * Gets the value of the totales property.
     *
     * @return possible object is {@link TotalesType }
     *
     */
    public TotalesType getTotales() {
        return totales;
    }

    /**
     * Sets the value of the totales property.
     *
     * @param value allowed object is {@link TotalesType }
     *
     */
    public void setTotales(TotalesType value) {
        this.totales = value;
    }

    /**
     * Gets the value of the composicionPortafolio property.
     *
     * @return possible object is {@link ComposicionPortafolioType }
     *
     */
    public ComposicionPortafolioType getComposicionPortafolio() {
        return composicionPortafolio;
    }

    /**
     * Sets the value of the composicionPortafolio property.
     *
     * @param value allowed object is {@link ComposicionPortafolioType }
     *
     */
    public void setComposicionPortafolio(ComposicionPortafolioType value) {
        this.composicionPortafolio = value;
    }

    /**
     * Gets the value of the cheques property.
     *
     * @return possible object is {@link ChequesType }
     *
     */
    public ChequesType getCheques() {
        return cheques;
    }

    /**
     * Sets the value of the cheques property.
     *
     * @param value allowed object is {@link ChequesType }
     *
     */
    public void setCheques(ChequesType value) {
        this.cheques = value;
    }

    /**
     * Gets the value of the evolucionDeuda property.
     *
     * @return possible object is {@link EvolucionDeudaType }
     *
     */
    public EvolucionDeudaType getEvolucionDeuda() {
        return evolucionDeuda;
    }

    /**
     * Sets the value of the evolucionDeuda property.
     *
     * @param value allowed object is {@link EvolucionDeudaType }
     *
     */
    public void setEvolucionDeuda(EvolucionDeudaType value) {
        this.evolucionDeuda = value;
    }

    /**
     * Gets the value of the historicoSaldos property.
     *
     * @return possible object is {@link HistoricoSaldosType }
     *
     */
    public HistoricoSaldosType getHistoricoSaldos() {
        return historicoSaldos;
    }

    /**
     * Sets the value of the historicoSaldos property.
     *
     * @param value allowed object is {@link HistoricoSaldosType }
     *
     */
    public void setHistoricoSaldos(HistoricoSaldosType value) {
        this.historicoSaldos = value;
    }

    /**
     * Gets the value of the resumenEndeudamiento property.
     *
     * @return possible object is {@link ResumenEndeudamientoType }
     *
     */
    public ResumenEndeudamientoType getResumenEndeudamiento() {
        return resumenEndeudamiento;
    }

    /**
     * Sets the value of the resumenEndeudamiento property.
     *
     * @param value allowed object is {@link ResumenEndeudamientoType }
     *
     */
    public void setResumenEndeudamiento(ResumenEndeudamientoType value) {
        this.resumenEndeudamiento = value;
    }

}
