//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for NaturalNacionalType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="NaturalNacionalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Identificacion">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="numero" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="estado" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="fechaExpedicion" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="ciudad" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="departamento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="EstadoCivil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="genero" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Edad" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="min" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Ubicacion" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="antiguedad" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="tipo">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InfoDemografica" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{}InfoDemograficaType">
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="nombres" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="primerApellido" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="segundoApellido" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nombreCompleto" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="validada" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="rut" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="EstadoCivil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="genero" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NaturalNacionalType", propOrder = {
    "identificacion",
    "edad",
    "ubicacion",
    "infoDemografica"
})
public class NaturalNacionalType {

    @XmlElement(name = "Identificacion", required = true)
    protected NaturalNacionalType.Identificacion identificacion;
    @XmlElement(name = "Edad")
    protected NaturalNacionalType.Edad edad;
    @XmlElement(name = "Ubicacion")
    protected NaturalNacionalType.Ubicacion ubicacion;
    @XmlElement(name = "InfoDemografica")
    protected NaturalNacionalType.InfoDemografica infoDemografica;
    @XmlAttribute
    protected String nombres;
    @XmlAttribute
    protected String primerApellido;
    @XmlAttribute
    protected String segundoApellido;
    @XmlAttribute(required = true)
    protected String nombreCompleto;
    @XmlAttribute(required = true)
    protected boolean validada;
    @XmlAttribute(required = true)
    protected boolean rut;
    @XmlAttribute(name = "EstadoCivil")
    protected String estadoCivil;
    @XmlAttribute
    protected Integer genero;

    /**
     * Gets the value of the identificacion property.
     *
     * @return possible object is {@link NaturalNacionalType.Identificacion }
     *
     */
    public NaturalNacionalType.Identificacion getIdentificacion() {
        return identificacion;
    }

    /**
     * Sets the value of the identificacion property.
     *
     * @param value allowed object is
     *     {@link NaturalNacionalType.Identificacion }
     *
     */
    public void setIdentificacion(NaturalNacionalType.Identificacion value) {
        this.identificacion = value;
    }

    /**
     * Gets the value of the edad property.
     *
     * @return possible object is {@link NaturalNacionalType.Edad }
     *
     */
    public NaturalNacionalType.Edad getEdad() {
        return edad;
    }

    /**
     * Sets the value of the edad property.
     *
     * @param value allowed object is {@link NaturalNacionalType.Edad }
     *
     */
    public void setEdad(NaturalNacionalType.Edad value) {
        this.edad = value;
    }

    /**
     * Gets the value of the ubicacion property.
     *
     * @return possible object is {@link NaturalNacionalType.Ubicacion }
     *
     */
    public NaturalNacionalType.Ubicacion getUbicacion() {
        return ubicacion;
    }

    /**
     * Sets the value of the ubicacion property.
     *
     * @param value allowed object is {@link NaturalNacionalType.Ubicacion }
     *
     */
    public void setUbicacion(NaturalNacionalType.Ubicacion value) {
        this.ubicacion = value;
    }

    /**
     * Gets the value of the infoDemografica property.
     *
     * @return possible object is {@link NaturalNacionalType.InfoDemografica }
     *
     */
    public NaturalNacionalType.InfoDemografica getInfoDemografica() {
        return infoDemografica;
    }

    /**
     * Sets the value of the infoDemografica property.
     *
     * @param value allowed object is
     *     {@link NaturalNacionalType.InfoDemografica }
     *
     */
    public void setInfoDemografica(NaturalNacionalType.InfoDemografica value) {
        this.infoDemografica = value;
    }

    /**
     * Gets the value of the nombres property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNombres() {
        return nombres;
    }

    /**
     * Sets the value of the nombres property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNombres(String value) {
        this.nombres = value;
    }

    /**
     * Gets the value of the primerApellido property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPrimerApellido() {
        return primerApellido;
    }

    /**
     * Sets the value of the primerApellido property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPrimerApellido(String value) {
        this.primerApellido = value;
    }

    /**
     * Gets the value of the segundoApellido property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSegundoApellido() {
        return segundoApellido;
    }

    /**
     * Sets the value of the segundoApellido property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSegundoApellido(String value) {
        this.segundoApellido = value;
    }

    /**
     * Gets the value of the nombreCompleto property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNombreCompleto() {
        return nombreCompleto;
    }

    /**
     * Sets the value of the nombreCompleto property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNombreCompleto(String value) {
        this.nombreCompleto = value;
    }

    /**
     * Gets the value of the validada property.
     *
     * @return 
     */
    public boolean isValidada() {
        return validada;
    }

    /**
     * Sets the value of the validada property.
     *
     * @param value
     */
    public void setValidada(boolean value) {
        this.validada = value;
    }

    /**
     * Gets the value of the rut property.
     *
     * @return 
     */
    public boolean isRut() {
        return rut;
    }

    /**
     * Sets the value of the rut property.
     *
     * @param value
     */
    public void setRut(boolean value) {
        this.rut = value;
    }

    /**
     * Gets the value of the estadoCivil property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEstadoCivil() {
        return estadoCivil;
    }

    /**
     * Sets the value of the estadoCivil property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEstadoCivil(String value) {
        this.estadoCivil = value;
    }

    /**
     * Gets the value of the genero property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getGenero() {
        return genero;
    }

    /**
     * Sets the value of the genero property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setGenero(Integer value) {
        this.genero = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="min" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Edad {

        @XmlAttribute(required = true)
        protected int min;
        @XmlAttribute
        protected Integer max;

        /**
         * Gets the value of the min property.
         *
         * @return 
         */
        public int getMin() {
            return min;
        }

        /**
         * Sets the value of the min property.
         *
         * @param value
         */
        public void setMin(int value) {
            this.min = value;
        }

        /**
         * Gets the value of the max property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getMax() {
            return max;
        }

        /**
         * Sets the value of the max property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setMax(Integer value) {
            this.max = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="numero" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="estado" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="fechaExpedicion" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="ciudad" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="departamento" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="EstadoCivil" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="genero" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Identificacion {

        @XmlAttribute(required = true)
        protected String numero;
        @XmlAttribute
        protected String estado;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar fechaExpedicion;
        @XmlAttribute
        protected String ciudad;
        @XmlAttribute
        protected String departamento;
        @XmlAttribute(name = "EstadoCivil")
        protected String estadoCivil;
        @XmlAttribute
        protected String genero;

        /**
         * Gets the value of the numero property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getNumero() {
            return numero;
        }

        /**
         * Sets the value of the numero property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setNumero(String value) {
            this.numero = value;
        }

        /**
         * Gets the value of the estado property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setEstado(String value) {
            this.estado = value;
        }

        /**
         * Gets the value of the fechaExpedicion property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getFechaExpedicion() {
            return fechaExpedicion;
        }

        /**
         * Sets the value of the fechaExpedicion property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setFechaExpedicion(XMLGregorianCalendar value) {
            this.fechaExpedicion = value;
        }

        /**
         * Gets the value of the ciudad property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getCiudad() {
            return ciudad;
        }

        /**
         * Sets the value of the ciudad property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setCiudad(String value) {
            this.ciudad = value;
        }

        /**
         * Gets the value of the departamento property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getDepartamento() {
            return departamento;
        }

        /**
         * Sets the value of the departamento property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setDepartamento(String value) {
            this.departamento = value;
        }

        /**
         * Gets the value of the estadoCivil property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getEstadoCivil() {
            return estadoCivil;
        }

        /**
         * Sets the value of the estadoCivil property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setEstadoCivil(String value) {
            this.estadoCivil = value;
        }

        /**
         * Gets the value of the genero property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getGenero() {
            return genero;
        }

        /**
         * Sets the value of the genero property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setGenero(String value) {
            this.genero = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{}InfoDemograficaType">
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class InfoDemografica
            extends InfoDemograficaType {

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="antiguedad" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="tipo">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Ubicacion {

        @XmlAttribute
        protected Integer antiguedad;
        @XmlAttribute
        protected String tipo;

        /**
         * Gets the value of the antiguedad property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getAntiguedad() {
            return antiguedad;
        }

        /**
         * Sets the value of the antiguedad property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setAntiguedad(Integer value) {
            this.antiguedad = value;
        }

        /**
         * Gets the value of the tipo property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getTipo() {
            return tipo;
        }

        /**
         * Sets the value of the tipo property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setTipo(String value) {
            this.tipo = value;
        }

    }

}
