//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for productosValoresType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="productosValoresType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="razon10" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="razon9" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="razon8" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="razon7" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="razon6" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="razon5" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="razon4" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="razon3" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="razon2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="razon1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor10smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor9smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor8smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor7smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor6smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor5smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor4smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor3smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor2smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor1smlv" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor10" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor9" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor8" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor7" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor6" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor5" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor4" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor3" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor2" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valor1" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="clasificacion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="producto" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productosValoresType")
public class ProductosValoresType {

    @XmlAttribute
    protected String razon10;
    @XmlAttribute
    protected String razon9;
    @XmlAttribute
    protected String razon8;
    @XmlAttribute
    protected String razon7;
    @XmlAttribute
    protected String razon6;
    @XmlAttribute
    protected String razon5;
    @XmlAttribute
    protected String razon4;
    @XmlAttribute
    protected String razon3;
    @XmlAttribute
    protected String razon2;
    @XmlAttribute
    protected String razon1;
    @XmlAttribute(name = "valor10smlv")
    protected String valor10Smlv;
    @XmlAttribute(name = "valor9smlv")
    protected String valor9Smlv;
    @XmlAttribute(name = "valor8smlv")
    protected String valor8Smlv;
    @XmlAttribute(name = "valor7smlv")
    protected String valor7Smlv;
    @XmlAttribute(name = "valor6smlv")
    protected String valor6Smlv;
    @XmlAttribute(name = "valor5smlv")
    protected String valor5Smlv;
    @XmlAttribute(name = "valor4smlv")
    protected String valor4Smlv;
    @XmlAttribute(name = "valor3smlv")
    protected String valor3Smlv;
    @XmlAttribute(name = "valor2smlv")
    protected String valor2Smlv;
    @XmlAttribute(name = "valor1smlv")
    protected String valor1Smlv;
    @XmlAttribute
    protected String valor10;
    @XmlAttribute
    protected String valor9;
    @XmlAttribute
    protected String valor8;
    @XmlAttribute
    protected String valor7;
    @XmlAttribute
    protected String valor6;
    @XmlAttribute
    protected String valor5;
    @XmlAttribute
    protected String valor4;
    @XmlAttribute
    protected String valor3;
    @XmlAttribute
    protected String valor2;
    @XmlAttribute
    protected String valor1;
    @XmlAttribute
    protected String clasificacion;
    @XmlAttribute(required = true)
    protected String producto;

    /**
     * Gets the value of the razon10 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon10() {
        return razon10;
    }

    /**
     * Sets the value of the razon10 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon10(String value) {
        this.razon10 = value;
    }

    /**
     * Gets the value of the razon9 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon9() {
        return razon9;
    }

    /**
     * Sets the value of the razon9 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon9(String value) {
        this.razon9 = value;
    }

    /**
     * Gets the value of the razon8 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon8() {
        return razon8;
    }

    /**
     * Sets the value of the razon8 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon8(String value) {
        this.razon8 = value;
    }

    /**
     * Gets the value of the razon7 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon7() {
        return razon7;
    }

    /**
     * Sets the value of the razon7 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon7(String value) {
        this.razon7 = value;
    }

    /**
     * Gets the value of the razon6 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon6() {
        return razon6;
    }

    /**
     * Sets the value of the razon6 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon6(String value) {
        this.razon6 = value;
    }

    /**
     * Gets the value of the razon5 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon5() {
        return razon5;
    }

    /**
     * Sets the value of the razon5 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon5(String value) {
        this.razon5 = value;
    }

    /**
     * Gets the value of the razon4 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon4() {
        return razon4;
    }

    /**
     * Sets the value of the razon4 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon4(String value) {
        this.razon4 = value;
    }

    /**
     * Gets the value of the razon3 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon3() {
        return razon3;
    }

    /**
     * Sets the value of the razon3 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon3(String value) {
        this.razon3 = value;
    }

    /**
     * Gets the value of the razon2 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon2() {
        return razon2;
    }

    /**
     * Sets the value of the razon2 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon2(String value) {
        this.razon2 = value;
    }

    /**
     * Gets the value of the razon1 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getRazon1() {
        return razon1;
    }

    /**
     * Sets the value of the razon1 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setRazon1(String value) {
        this.razon1 = value;
    }

    /**
     * Gets the value of the valor10Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor10Smlv() {
        return valor10Smlv;
    }

    /**
     * Sets the value of the valor10Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor10Smlv(String value) {
        this.valor10Smlv = value;
    }

    /**
     * Gets the value of the valor9Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor9Smlv() {
        return valor9Smlv;
    }

    /**
     * Sets the value of the valor9Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor9Smlv(String value) {
        this.valor9Smlv = value;
    }

    /**
     * Gets the value of the valor8Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor8Smlv() {
        return valor8Smlv;
    }

    /**
     * Sets the value of the valor8Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor8Smlv(String value) {
        this.valor8Smlv = value;
    }

    /**
     * Gets the value of the valor7Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor7Smlv() {
        return valor7Smlv;
    }

    /**
     * Sets the value of the valor7Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor7Smlv(String value) {
        this.valor7Smlv = value;
    }

    /**
     * Gets the value of the valor6Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor6Smlv() {
        return valor6Smlv;
    }

    /**
     * Sets the value of the valor6Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor6Smlv(String value) {
        this.valor6Smlv = value;
    }

    /**
     * Gets the value of the valor5Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor5Smlv() {
        return valor5Smlv;
    }

    /**
     * Sets the value of the valor5Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor5Smlv(String value) {
        this.valor5Smlv = value;
    }

    /**
     * Gets the value of the valor4Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor4Smlv() {
        return valor4Smlv;
    }

    /**
     * Sets the value of the valor4Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor4Smlv(String value) {
        this.valor4Smlv = value;
    }

    /**
     * Gets the value of the valor3Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor3Smlv() {
        return valor3Smlv;
    }

    /**
     * Sets the value of the valor3Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor3Smlv(String value) {
        this.valor3Smlv = value;
    }

    /**
     * Gets the value of the valor2Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor2Smlv() {
        return valor2Smlv;
    }

    /**
     * Sets the value of the valor2Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor2Smlv(String value) {
        this.valor2Smlv = value;
    }

    /**
     * Gets the value of the valor1Smlv property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor1Smlv() {
        return valor1Smlv;
    }

    /**
     * Sets the value of the valor1Smlv property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor1Smlv(String value) {
        this.valor1Smlv = value;
    }

    /**
     * Gets the value of the valor10 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor10() {
        return valor10;
    }

    /**
     * Sets the value of the valor10 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor10(String value) {
        this.valor10 = value;
    }

    /**
     * Gets the value of the valor9 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor9() {
        return valor9;
    }

    /**
     * Sets the value of the valor9 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor9(String value) {
        this.valor9 = value;
    }

    /**
     * Gets the value of the valor8 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor8() {
        return valor8;
    }

    /**
     * Sets the value of the valor8 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor8(String value) {
        this.valor8 = value;
    }

    /**
     * Gets the value of the valor7 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor7() {
        return valor7;
    }

    /**
     * Sets the value of the valor7 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor7(String value) {
        this.valor7 = value;
    }

    /**
     * Gets the value of the valor6 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor6() {
        return valor6;
    }

    /**
     * Sets the value of the valor6 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor6(String value) {
        this.valor6 = value;
    }

    /**
     * Gets the value of the valor5 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor5() {
        return valor5;
    }

    /**
     * Sets the value of the valor5 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor5(String value) {
        this.valor5 = value;
    }

    /**
     * Gets the value of the valor4 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor4() {
        return valor4;
    }

    /**
     * Sets the value of the valor4 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor4(String value) {
        this.valor4 = value;
    }

    /**
     * Gets the value of the valor3 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor3() {
        return valor3;
    }

    /**
     * Sets the value of the valor3 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor3(String value) {
        this.valor3 = value;
    }

    /**
     * Gets the value of the valor2 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor2() {
        return valor2;
    }

    /**
     * Sets the value of the valor2 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor2(String value) {
        this.valor2 = value;
    }

    /**
     * Gets the value of the valor1 property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getValor1() {
        return valor1;
    }

    /**
     * Sets the value of the valor1 property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setValor1(String value) {
        this.valor1 = value;
    }

    /**
     * Gets the value of the clasificacion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getClasificacion() {
        return clasificacion;
    }

    /**
     * Sets the value of the clasificacion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setClasificacion(String value) {
        this.clasificacion = value;
    }

    /**
     * Gets the value of the producto property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getProducto() {
        return producto;
    }

    /**
     * Sets the value of the producto property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setProducto(String value) {
        this.producto = value;
    }

}
