//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ResumenMicrocreditoType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ResumenMicrocreditoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="PerfilGeneral" type="{}PerfilGeneralType" minOccurs="0"/>
 *         &lt;element name="VectorSaldosYMoras" type="{}VectorSaldosYMorasType" minOccurs="0"/>
 *         &lt;element name="EndeudamientoActual" type="{}EndeudamientoActualType" minOccurs="0"/>
 *         &lt;element name="ImagenTendenciaEndeudamiento" type="{}ImagenTendenciaEndeudamientoType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResumenMicrocreditoType", propOrder = {
    "perfilGeneral",
    "vectorSaldosYMoras",
    "endeudamientoActual",
    "imagenTendenciaEndeudamiento"
})
public class ResumenMicrocreditoType {

    @XmlElement(name = "PerfilGeneral")
    protected PerfilGeneralType perfilGeneral;
    @XmlElement(name = "VectorSaldosYMoras")
    protected VectorSaldosYMorasType vectorSaldosYMoras;
    @XmlElement(name = "EndeudamientoActual")
    protected EndeudamientoActualType endeudamientoActual;
    @XmlElement(name = "ImagenTendenciaEndeudamiento")
    protected ImagenTendenciaEndeudamientoType imagenTendenciaEndeudamiento;

    /**
     * Gets the value of the perfilGeneral property.
     *
     * @return possible object is {@link PerfilGeneralType }
     *
     */
    public PerfilGeneralType getPerfilGeneral() {
        return perfilGeneral;
    }

    /**
     * Sets the value of the perfilGeneral property.
     *
     * @param value allowed object is {@link PerfilGeneralType }
     *
     */
    public void setPerfilGeneral(PerfilGeneralType value) {
        this.perfilGeneral = value;
    }

    /**
     * Gets the value of the vectorSaldosYMoras property.
     *
     * @return possible object is {@link VectorSaldosYMorasType }
     *
     */
    public VectorSaldosYMorasType getVectorSaldosYMoras() {
        return vectorSaldosYMoras;
    }

    /**
     * Sets the value of the vectorSaldosYMoras property.
     *
     * @param value allowed object is {@link VectorSaldosYMorasType }
     *
     */
    public void setVectorSaldosYMoras(VectorSaldosYMorasType value) {
        this.vectorSaldosYMoras = value;
    }

    /**
     * Gets the value of the endeudamientoActual property.
     *
     * @return possible object is {@link EndeudamientoActualType }
     *
     */
    public EndeudamientoActualType getEndeudamientoActual() {
        return endeudamientoActual;
    }

    /**
     * Sets the value of the endeudamientoActual property.
     *
     * @param value allowed object is {@link EndeudamientoActualType }
     *
     */
    public void setEndeudamientoActual(EndeudamientoActualType value) {
        this.endeudamientoActual = value;
    }

    /**
     * Gets the value of the imagenTendenciaEndeudamiento property.
     *
     * @return possible object is {@link ImagenTendenciaEndeudamientoType }
     *
     */
    public ImagenTendenciaEndeudamientoType getImagenTendenciaEndeudamiento() {
        return imagenTendenciaEndeudamiento;
    }

    /**
     * Sets the value of the imagenTendenciaEndeudamiento property.
     *
     * @param value allowed object is {@link ImagenTendenciaEndeudamientoType }
     *
     */
    public void setImagenTendenciaEndeudamiento(ImagenTendenciaEndeudamientoType value) {
        this.imagenTendenciaEndeudamiento = value;
    }

}
