//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for ResumenType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ResumenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Principales">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="creditoVigentes" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="creditosCerrados" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="creditosActualesNegativos" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="histNegUlt12Meses" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="cuentasAbiertasAHOCCB" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="cuentasCerradasAHOCCB" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="consultadasUlt6meses" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="desacuerdosALaFecha" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="antiguedadDesde" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                 &lt;attribute name="reclamosVigentes" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Saldos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="Sector" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="sector" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="participacion" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Mes" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="saldoTotalMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="saldoTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="saldoTotalEnMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="saldoM30" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="saldoM60" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="saldoM90" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="cuotaMensual" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="saldoCreditoMasAlto" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="saldoTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Comportamiento">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="Mes" maxOccurs="24">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="comportamiento" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *                           &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResumenType", propOrder = {
    "principales",
    "saldos",
    "comportamiento"
})
public class ResumenType {

    @XmlElement(name = "Principales", required = true)
    protected ResumenType.Principales principales;
    @XmlElement(name = "Saldos", required = true)
    protected ResumenType.Saldos saldos;
    @XmlElement(name = "Comportamiento", required = true)
    protected ResumenType.Comportamiento comportamiento;

    /**
     * Gets the value of the principales property.
     *
     * @return possible object is {@link ResumenType.Principales }
     *
     */
    public ResumenType.Principales getPrincipales() {
        return principales;
    }

    /**
     * Sets the value of the principales property.
     *
     * @param value allowed object is {@link ResumenType.Principales }
     *
     */
    public void setPrincipales(ResumenType.Principales value) {
        this.principales = value;
    }

    /**
     * Gets the value of the saldos property.
     *
     * @return possible object is {@link ResumenType.Saldos }
     *
     */
    public ResumenType.Saldos getSaldos() {
        return saldos;
    }

    /**
     * Sets the value of the saldos property.
     *
     * @param value allowed object is {@link ResumenType.Saldos }
     *
     */
    public void setSaldos(ResumenType.Saldos value) {
        this.saldos = value;
    }

    /**
     * Gets the value of the comportamiento property.
     *
     * @return possible object is {@link ResumenType.Comportamiento }
     *
     */
    public ResumenType.Comportamiento getComportamiento() {
        return comportamiento;
    }

    /**
     * Sets the value of the comportamiento property.
     *
     * @param value allowed object is {@link ResumenType.Comportamiento }
     *
     */
    public void setComportamiento(ResumenType.Comportamiento value) {
        this.comportamiento = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="Mes" maxOccurs="24">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="comportamiento" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
     *                 &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mes"
    })
    public static class Comportamiento {

        @XmlElement(name = "Mes")
        protected List<ResumenType.Comportamiento.Mes> mes;

        /**
         * Gets the value of the mes property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the mes property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMes().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResumenType.Comportamiento.Mes }
         *
         *
         * @return 
         */
        public List<ResumenType.Comportamiento.Mes> getMes() {
            if (mes == null) {
                mes = new ArrayList<ResumenType.Comportamiento.Mes>();
            }
            return this.mes;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="comportamiento" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
         *       &lt;attribute name="cantidad" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Mes {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fecha;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "anySimpleType")
            protected String comportamiento;
            @XmlAttribute(required = true)
            protected int cantidad;

            /**
             * Gets the value of the fecha property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

            /**
             * Gets the value of the comportamiento property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getComportamiento() {
                return comportamiento;
            }

            /**
             * Sets the value of the comportamiento property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setComportamiento(String value) {
                this.comportamiento = value;
            }

            /**
             * Gets the value of the cantidad property.
             *
             * @return 
             */
            public int getCantidad() {
                return cantidad;
            }

            /**
             * Sets the value of the cantidad property.
             *
             * @param value
             */
            public void setCantidad(int value) {
                this.cantidad = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="creditoVigentes" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="creditosCerrados" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="creditosActualesNegativos" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="histNegUlt12Meses" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="cuentasAbiertasAHOCCB" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="cuentasCerradasAHOCCB" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="consultadasUlt6meses" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="desacuerdosALaFecha" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="antiguedadDesde" type="{http://www.w3.org/2001/XMLSchema}date" />
     *       &lt;attribute name="reclamosVigentes" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Principales {

        @XmlAttribute
        protected Integer creditoVigentes;
        @XmlAttribute
        protected Integer creditosCerrados;
        @XmlAttribute
        protected Integer creditosActualesNegativos;
        @XmlAttribute
        protected Integer histNegUlt12Meses;
        @XmlAttribute
        protected Integer cuentasAbiertasAHOCCB;
        @XmlAttribute
        protected Integer cuentasCerradasAHOCCB;
        @XmlAttribute(name = "consultadasUlt6meses")
        protected Integer consultadasUlt6Meses;
        @XmlAttribute
        protected Integer desacuerdosALaFecha;
        @XmlAttribute
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar antiguedadDesde;
        @XmlAttribute
        protected Integer reclamosVigentes;

        /**
         * Gets the value of the creditoVigentes property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getCreditoVigentes() {
            return creditoVigentes;
        }

        /**
         * Sets the value of the creditoVigentes property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setCreditoVigentes(Integer value) {
            this.creditoVigentes = value;
        }

        /**
         * Gets the value of the creditosCerrados property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getCreditosCerrados() {
            return creditosCerrados;
        }

        /**
         * Sets the value of the creditosCerrados property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setCreditosCerrados(Integer value) {
            this.creditosCerrados = value;
        }

        /**
         * Gets the value of the creditosActualesNegativos property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getCreditosActualesNegativos() {
            return creditosActualesNegativos;
        }

        /**
         * Sets the value of the creditosActualesNegativos property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setCreditosActualesNegativos(Integer value) {
            this.creditosActualesNegativos = value;
        }

        /**
         * Gets the value of the histNegUlt12Meses property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getHistNegUlt12Meses() {
            return histNegUlt12Meses;
        }

        /**
         * Sets the value of the histNegUlt12Meses property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setHistNegUlt12Meses(Integer value) {
            this.histNegUlt12Meses = value;
        }

        /**
         * Gets the value of the cuentasAbiertasAHOCCB property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getCuentasAbiertasAHOCCB() {
            return cuentasAbiertasAHOCCB;
        }

        /**
         * Sets the value of the cuentasAbiertasAHOCCB property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setCuentasAbiertasAHOCCB(Integer value) {
            this.cuentasAbiertasAHOCCB = value;
        }

        /**
         * Gets the value of the cuentasCerradasAHOCCB property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getCuentasCerradasAHOCCB() {
            return cuentasCerradasAHOCCB;
        }

        /**
         * Sets the value of the cuentasCerradasAHOCCB property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setCuentasCerradasAHOCCB(Integer value) {
            this.cuentasCerradasAHOCCB = value;
        }

        /**
         * Gets the value of the consultadasUlt6Meses property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getConsultadasUlt6Meses() {
            return consultadasUlt6Meses;
        }

        /**
         * Sets the value of the consultadasUlt6Meses property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setConsultadasUlt6Meses(Integer value) {
            this.consultadasUlt6Meses = value;
        }

        /**
         * Gets the value of the desacuerdosALaFecha property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getDesacuerdosALaFecha() {
            return desacuerdosALaFecha;
        }

        /**
         * Sets the value of the desacuerdosALaFecha property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setDesacuerdosALaFecha(Integer value) {
            this.desacuerdosALaFecha = value;
        }

        /**
         * Gets the value of the antiguedadDesde property.
         *
         * @return possible object is {@link XMLGregorianCalendar }
         *
         */
        public XMLGregorianCalendar getAntiguedadDesde() {
            return antiguedadDesde;
        }

        /**
         * Sets the value of the antiguedadDesde property.
         *
         * @param value allowed object is {@link XMLGregorianCalendar }
         *
         */
        public void setAntiguedadDesde(XMLGregorianCalendar value) {
            this.antiguedadDesde = value;
        }

        /**
         * Gets the value of the reclamosVigentes property.
         *
         * @return possible object is {@link Integer }
         *
         */
        public Integer getReclamosVigentes() {
            return reclamosVigentes;
        }

        /**
         * Sets the value of the reclamosVigentes property.
         *
         * @param value allowed object is {@link Integer }
         *
         */
        public void setReclamosVigentes(Integer value) {
            this.reclamosVigentes = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="Sector" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="sector" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="participacion" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Mes" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="saldoTotalMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="saldoTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="saldoTotalEnMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="saldoM30" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="saldoM60" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="saldoM90" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="cuotaMensual" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="saldoCreditoMasAlto" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="saldoTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sector",
        "mes"
    })
    public static class Saldos {

        @XmlElement(name = "Sector")
        protected List<ResumenType.Saldos.Sector> sector;
        @XmlElement(name = "Mes")
        protected List<ResumenType.Saldos.Mes> mes;
        @XmlAttribute(required = true)
        protected double saldoTotalEnMora;
        @XmlAttribute(required = true)
        protected double saldoM30;
        @XmlAttribute(required = true)
        protected double saldoM60;
        @XmlAttribute(required = true)
        protected double saldoM90;
        @XmlAttribute(required = true)
        protected double cuotaMensual;
        @XmlAttribute(required = true)
        protected double saldoCreditoMasAlto;
        @XmlAttribute(required = true)
        protected double saldoTotal;

        /**
         * Gets the value of the sector property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the sector property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSector().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResumenType.Saldos.Sector }
         *
         *
         * @return 
         */
        public List<ResumenType.Saldos.Sector> getSector() {
            if (sector == null) {
                sector = new ArrayList<ResumenType.Saldos.Sector>();
            }
            return this.sector;
        }

        /**
         * Gets the value of the mes property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the mes property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMes().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResumenType.Saldos.Mes }
         *
         *
         * @return 
         */
        public List<ResumenType.Saldos.Mes> getMes() {
            if (mes == null) {
                mes = new ArrayList<ResumenType.Saldos.Mes>();
            }
            return this.mes;
        }

        /**
         * Gets the value of the saldoTotalEnMora property.
         *
         * @return 
         */
        public double getSaldoTotalEnMora() {
            return saldoTotalEnMora;
        }

        /**
         * Sets the value of the saldoTotalEnMora property.
         *
         * @param value
         */
        public void setSaldoTotalEnMora(double value) {
            this.saldoTotalEnMora = value;
        }

        /**
         * Gets the value of the saldoM30 property.
         *
         * @return 
         */
        public double getSaldoM30() {
            return saldoM30;
        }

        /**
         * Sets the value of the saldoM30 property.
         *
         * @param value
         */
        public void setSaldoM30(double value) {
            this.saldoM30 = value;
        }

        /**
         * Gets the value of the saldoM60 property.
         *
         * @return 
         */
        public double getSaldoM60() {
            return saldoM60;
        }

        /**
         * Sets the value of the saldoM60 property.
         *
         * @param value
         */
        public void setSaldoM60(double value) {
            this.saldoM60 = value;
        }

        /**
         * Gets the value of the saldoM90 property.
         *
         * @return 
         */
        public double getSaldoM90() {
            return saldoM90;
        }

        /**
         * Sets the value of the saldoM90 property.
         *
         * @param value
         */
        public void setSaldoM90(double value) {
            this.saldoM90 = value;
        }

        /**
         * Gets the value of the cuotaMensual property.
         *
         * @return 
         */
        public double getCuotaMensual() {
            return cuotaMensual;
        }

        /**
         * Sets the value of the cuotaMensual property.
         *
         * @param value
         */
        public void setCuotaMensual(double value) {
            this.cuotaMensual = value;
        }

        /**
         * Gets the value of the saldoCreditoMasAlto property.
         *
         * @return 
         */
        public double getSaldoCreditoMasAlto() {
            return saldoCreditoMasAlto;
        }

        /**
         * Sets the value of the saldoCreditoMasAlto property.
         *
         * @param value
         */
        public void setSaldoCreditoMasAlto(double value) {
            this.saldoCreditoMasAlto = value;
        }

        /**
         * Gets the value of the saldoTotal property.
         *
         * @return 
         */
        public double getSaldoTotal() {
            return saldoTotal;
        }

        /**
         * Sets the value of the saldoTotal property.
         *
         * @param value
         */
        public void setSaldoTotal(double value) {
            this.saldoTotal = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="saldoTotalMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="saldoTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Mes {

            @XmlAttribute(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fecha;
            @XmlAttribute(required = true)
            protected double saldoTotalMora;
            @XmlAttribute(required = true)
            protected double saldoTotal;

            /**
             * Gets the value of the fecha property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

            /**
             * Gets the value of the saldoTotalMora property.
             *
             * @return 
             */
            public double getSaldoTotalMora() {
                return saldoTotalMora;
            }

            /**
             * Sets the value of the saldoTotalMora property.
             *
             * @param value
             */
            public void setSaldoTotalMora(double value) {
                this.saldoTotalMora = value;
            }

            /**
             * Gets the value of the saldoTotal property.
             *
             * @return 
             */
            public double getSaldoTotal() {
                return saldoTotal;
            }

            /**
             * Sets the value of the saldoTotal property.
             *
             * @param value
             */
            public void setSaldoTotal(double value) {
                this.saldoTotal = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="sector" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="saldo" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="participacion" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Sector {

            @XmlAttribute(required = true)
            protected int sector;
            @XmlAttribute(required = true)
            protected double saldo;
            @XmlAttribute(required = true)
            protected double participacion;

            /**
             * Gets the value of the sector property.
             *
             * @return 
             */
            public int getSector() {
                return sector;
            }

            /**
             * Sets the value of the sector property.
             *
             * @param value
             */
            public void setSector(int value) {
                this.sector = value;
            }

            /**
             * Gets the value of the saldo property.
             *
             * @return 
             */
            public double getSaldo() {
                return saldo;
            }

            /**
             * Sets the value of the saldo property.
             *
             * @param value
             */
            public void setSaldo(double value) {
                this.saldo = value;
            }

            /**
             * Gets the value of the participacion property.
             *
             * @return 
             */
            public double getParticipacion() {
                return participacion;
            }

            /**
             * Sets the value of the participacion property.
             *
             * @param value
             */
            public void setParticipacion(double value) {
                this.participacion = value;
            }

        }

    }

}
