//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for ScoreType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ScoreType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Razon" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="tipo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="puntaje" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="clasificacion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="poblacion" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="nombreScore" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScoreType", propOrder = {
    "razon"
})
public class ScoreType {

    @XmlElement(name = "Razon")
    protected List<ScoreType.Razon> razon;
    @XmlAttribute(required = true)
    protected String tipo;
    @XmlAttribute(required = true)
    protected double puntaje;
    @XmlAttribute
    protected String clasificacion;
    @XmlAttribute
    protected Integer poblacion;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fecha;
    @XmlAttribute
    protected String nombreScore;

    /**
     * Gets the value of the razon property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the razon property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRazon().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreType.Razon }
     *
     *
     */
    public List<ScoreType.Razon> getRazon() {
        if (razon == null) {
            razon = new ArrayList<ScoreType.Razon>();
        }
        return this.razon;
    }

    /**
     * Gets the value of the tipo property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * Sets the value of the tipo property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTipo(String value) {
        this.tipo = value;
    }

    /**
     * Gets the value of the puntaje property.
     *
     */
    public double getPuntaje() {
        return puntaje;
    }

    /**
     * Sets the value of the puntaje property.
     *
     */
    public void setPuntaje(double value) {
        this.puntaje = value;
    }

    /**
     * Gets the value of the clasificacion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getClasificacion() {
        return clasificacion;
    }

    /**
     * Sets the value of the clasificacion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setClasificacion(String value) {
        this.clasificacion = value;
    }

    /**
     * Gets the value of the poblacion property.
     *
     * @return possible object is {@link Integer }
     *
     */
    public Integer getPoblacion() {
        return poblacion;
    }

    /**
     * Sets the value of the poblacion property.
     *
     * @param value allowed object is {@link Integer }
     *
     */
    public void setPoblacion(Integer value) {
        this.poblacion = value;
    }

    /**
     * Gets the value of the fecha property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFecha() {
        return fecha;
    }

    /**
     * Sets the value of the fecha property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setFecha(XMLGregorianCalendar value) {
        this.fecha = value;
    }

    /**
     * Gets the value of the nombreScore property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNombreScore() {
        return nombreScore;
    }

    /**
     * Sets the value of the nombreScore property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNombreScore(String value) {
        this.nombreScore = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Razon {

        @XmlAttribute(required = true)
        protected String codigo;

        /**
         * Gets the value of the codigo property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getCodigo() {
            return codigo;
        }

        /**
         * Sets the value of the codigo property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setCodigo(String value) {
            this.codigo = value;
        }

    }

}
