//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SectorEndeudamientoActualType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="SectorEndeudamientoActualType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="TipoCuenta" type="{}TipoCuentaType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="codSector" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SectorEndeudamientoActualType", propOrder = {
    "tipoCuenta"
})
public class SectorEndeudamientoActualType {

    @XmlElement(name = "TipoCuenta")
    protected List<TipoCuentaType> tipoCuenta;
    @XmlAttribute(required = true)
    protected int codSector;

    /**
     * Gets the value of the tipoCuenta property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the tipoCuenta property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipoCuenta().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipoCuentaType }
     *
     *
     * @return 
     */
    public List<TipoCuentaType> getTipoCuenta() {
        if (tipoCuenta == null) {
            tipoCuenta = new ArrayList<TipoCuentaType>();
        }
        return this.tipoCuenta;
    }

    /**
     * Gets the value of the codSector property.
     *
     * @return 
     */
    public int getCodSector() {
        return codSector;
    }

    /**
     * Sets the value of the codSector property.
     *
     * @param value
     */
    public void setCodSector(int value) {
        this.codSector = value;
    }

}
