//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for SeriesType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="SeriesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence minOccurs="0">
 *         &lt;element name="Valores" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Valor" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="valor" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="serie" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeriesType", propOrder = {
    "valores"
})
public class SeriesType {

    @XmlElement(name = "Valores")
    protected SeriesType.Valores valores;
    @XmlAttribute(required = true)
    protected String serie;

    /**
     * Gets the value of the valores property.
     *
     * @return possible object is {@link SeriesType.Valores }
     *
     */
    public SeriesType.Valores getValores() {
        return valores;
    }

    /**
     * Sets the value of the valores property.
     *
     * @param value allowed object is {@link SeriesType.Valores }
     *
     */
    public void setValores(SeriesType.Valores value) {
        this.valores = value;
    }

    /**
     * Gets the value of the serie property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSerie() {
        return serie;
    }

    /**
     * Sets the value of the serie property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSerie(String value) {
        this.serie = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Valor" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="valor" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "valor"
    })
    public static class Valores {

        @XmlElement(name = "Valor", required = true)
        protected List<SeriesType.Valores.Valor> valor;

        /**
         * Gets the value of the valor property.
         *
         * <p>
         * This accessor method returns a reference to the live list, not a
         * snapshot. Therefore any modification you make to the returned list
         * will be present inside the JAXB object. This is why there is not a
         * <CODE>set</CODE> method for the valor property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getValor().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SeriesType.Valores.Valor }
         *
         *
         * @return 
         */
        public List<SeriesType.Valores.Valor> getValor() {
            if (valor == null) {
                valor = new ArrayList<SeriesType.Valores.Valor>();
            }
            return this.valor;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="valor" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Valor {

            @XmlAttribute(required = true)
            protected double valor;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fecha;

            /**
             * Gets the value of the valor property.
             *
             * @return 
             */
            public double getValor() {
                return valor;
            }

            /**
             * Sets the value of the valor property.
             *
             * @param value
             */
            public void setValor(double value) {
                this.valor = value;
            }

            /**
             * Gets the value of the fecha property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

        }

    }

}
