//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.02 at 10:34:02 AM COT 
//
package com.jamar.historiacreditowss.jamarhistoriadecredito.generics;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for TarjetaCreditoType complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="TarjetaCreditoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Caracteristicas">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="codigoAmparada" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="franquicia" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="clase" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="marca" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="amparada" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                 &lt;attribute name="garantia" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Valores" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Valor" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="moneda" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="saldoActual" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="saldoMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="disponible" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="cuota" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="cupoTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="cuotasMora" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="diasMora" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="fechaPagoCuota" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="fechaLimitePago" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                           &lt;attribute name="calificacion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Estados">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EstadoPlastico">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EstadoCuenta">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EstadoOrigen">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="EstadoPago">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="meses" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Reclamo" type="{}ReclamoType" minOccurs="0"/>
 *         &lt;element name="Adjetivo" type="{}AdjetivoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Llave" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="bloqueada" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="entidad" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="numero" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fechaApertura" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="fechaVencimiento" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="comportamiento" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="formaPago" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="probabilidadIncumplimiento" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="calificacion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="situacionTitular" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="oficina" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ciudad" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codigoDaneCiudad" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="codSuscriptor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tipoIdentificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="identificacion" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sector" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="calificacionHD" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="independiente">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TarjetaCreditoType", propOrder = {
    "caracteristicas",
    "valores",
    "estados",
    "reclamo",
    "adjetivo",
    "llave"
})
public class TarjetaCreditoType {

    @XmlElement(name = "Caracteristicas", required = true)
    protected TarjetaCreditoType.Caracteristicas caracteristicas;
    @XmlElement(name = "Valores")
    protected TarjetaCreditoType.Valores valores;
    @XmlElement(name = "Estados", required = true)
    protected TarjetaCreditoType.Estados estados;
    @XmlElement(name = "Reclamo")
    protected ReclamoType reclamo;
    @XmlElement(name = "Adjetivo")
    protected List<AdjetivoType> adjetivo;
    @XmlElement(name = "Llave")
    protected String llave;
    @XmlAttribute(required = true)
    protected boolean bloqueada;
    @XmlAttribute(required = true)
    protected String entidad;
    @XmlAttribute(required = true)
    protected String numero;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaApertura;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaVencimiento;
    @XmlAttribute
    protected String comportamiento;
    @XmlAttribute
    protected String formaPago;
    @XmlAttribute
    protected Double probabilidadIncumplimiento;
    @XmlAttribute
    protected String calificacion;
    @XmlAttribute(required = true)
    protected String situacionTitular;
    @XmlAttribute
    protected String oficina;
    @XmlAttribute
    protected String ciudad;
    @XmlAttribute
    protected String codigoDaneCiudad;
    @XmlAttribute
    protected String codSuscriptor;
    @XmlAttribute(required = true)
    protected String tipoIdentificacion;
    @XmlAttribute(required = true)
    protected String identificacion;
    @XmlAttribute
    protected String sector;
    @XmlAttribute(required = true)
    protected boolean calificacionHD;
    @XmlAttribute
    protected String independiente;

    /**
     * Gets the value of the caracteristicas property.
     *
     * @return possible object is {@link TarjetaCreditoType.Caracteristicas }
     *
     */
    public TarjetaCreditoType.Caracteristicas getCaracteristicas() {
        return caracteristicas;
    }

    /**
     * Sets the value of the caracteristicas property.
     *
     * @param value allowed object is
     *     {@link TarjetaCreditoType.Caracteristicas }
     *
     */
    public void setCaracteristicas(TarjetaCreditoType.Caracteristicas value) {
        this.caracteristicas = value;
    }

    /**
     * Gets the value of the valores property.
     *
     * @return possible object is {@link TarjetaCreditoType.Valores }
     *
     */
    public TarjetaCreditoType.Valores getValores() {
        return valores;
    }

    /**
     * Sets the value of the valores property.
     *
     * @param value allowed object is {@link TarjetaCreditoType.Valores }
     *
     */
    public void setValores(TarjetaCreditoType.Valores value) {
        this.valores = value;
    }

    /**
     * Gets the value of the estados property.
     *
     * @return possible object is {@link TarjetaCreditoType.Estados }
     *
     */
    public TarjetaCreditoType.Estados getEstados() {
        return estados;
    }

    /**
     * Sets the value of the estados property.
     *
     * @param value allowed object is {@link TarjetaCreditoType.Estados }
     *
     */
    public void setEstados(TarjetaCreditoType.Estados value) {
        this.estados = value;
    }

    /**
     * Gets the value of the reclamo property.
     *
     * @return possible object is {@link ReclamoType }
     *
     */
    public ReclamoType getReclamo() {
        return reclamo;
    }

    /**
     * Sets the value of the reclamo property.
     *
     * @param value allowed object is {@link ReclamoType }
     *
     */
    public void setReclamo(ReclamoType value) {
        this.reclamo = value;
    }

    /**
     * Gets the value of the adjetivo property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the adjetivo property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjetivo().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdjetivoType }
     *
     *
     * @return 
     */
    public List<AdjetivoType> getAdjetivo() {
        if (adjetivo == null) {
            adjetivo = new ArrayList<AdjetivoType>();
        }
        return this.adjetivo;
    }

    /**
     * Gets the value of the llave property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getLlave() {
        return llave;
    }

    /**
     * Sets the value of the llave property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setLlave(String value) {
        this.llave = value;
    }

    /**
     * Gets the value of the bloqueada property.
     *
     * @return 
     */
    public boolean isBloqueada() {
        return bloqueada;
    }

    /**
     * Sets the value of the bloqueada property.
     *
     * @param value
     */
    public void setBloqueada(boolean value) {
        this.bloqueada = value;
    }

    /**
     * Gets the value of the entidad property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getEntidad() {
        return entidad;
    }

    /**
     * Sets the value of the entidad property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setEntidad(String value) {
        this.entidad = value;
    }

    /**
     * Gets the value of the numero property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the fechaApertura property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFechaApertura() {
        return fechaApertura;
    }

    /**
     * Sets the value of the fechaApertura property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setFechaApertura(XMLGregorianCalendar value) {
        this.fechaApertura = value;
    }

    /**
     * Gets the value of the fechaVencimiento property.
     *
     * @return possible object is {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFechaVencimiento() {
        return fechaVencimiento;
    }

    /**
     * Sets the value of the fechaVencimiento property.
     *
     * @param value allowed object is {@link XMLGregorianCalendar }
     *
     */
    public void setFechaVencimiento(XMLGregorianCalendar value) {
        this.fechaVencimiento = value;
    }

    /**
     * Gets the value of the comportamiento property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getComportamiento() {
        return comportamiento;
    }

    /**
     * Sets the value of the comportamiento property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setComportamiento(String value) {
        this.comportamiento = value;
    }

    /**
     * Gets the value of the formaPago property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFormaPago() {
        return formaPago;
    }

    /**
     * Sets the value of the formaPago property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFormaPago(String value) {
        this.formaPago = value;
    }

    /**
     * Gets the value of the probabilidadIncumplimiento property.
     *
     * @return possible object is {@link Double }
     *
     */
    public Double getProbabilidadIncumplimiento() {
        return probabilidadIncumplimiento;
    }

    /**
     * Sets the value of the probabilidadIncumplimiento property.
     *
     * @param value allowed object is {@link Double }
     *
     */
    public void setProbabilidadIncumplimiento(Double value) {
        this.probabilidadIncumplimiento = value;
    }

    /**
     * Gets the value of the calificacion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCalificacion() {
        return calificacion;
    }

    /**
     * Sets the value of the calificacion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCalificacion(String value) {
        this.calificacion = value;
    }

    /**
     * Gets the value of the situacionTitular property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSituacionTitular() {
        return situacionTitular;
    }

    /**
     * Sets the value of the situacionTitular property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSituacionTitular(String value) {
        this.situacionTitular = value;
    }

    /**
     * Gets the value of the oficina property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getOficina() {
        return oficina;
    }

    /**
     * Sets the value of the oficina property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setOficina(String value) {
        this.oficina = value;
    }

    /**
     * Gets the value of the ciudad property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCiudad() {
        return ciudad;
    }

    /**
     * Sets the value of the ciudad property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCiudad(String value) {
        this.ciudad = value;
    }

    /**
     * Gets the value of the codigoDaneCiudad property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCodigoDaneCiudad() {
        return codigoDaneCiudad;
    }

    /**
     * Sets the value of the codigoDaneCiudad property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCodigoDaneCiudad(String value) {
        this.codigoDaneCiudad = value;
    }

    /**
     * Gets the value of the codSuscriptor property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getCodSuscriptor() {
        return codSuscriptor;
    }

    /**
     * Sets the value of the codSuscriptor property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setCodSuscriptor(String value) {
        this.codSuscriptor = value;
    }

    /**
     * Gets the value of the tipoIdentificacion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getTipoIdentificacion() {
        return tipoIdentificacion;
    }

    /**
     * Sets the value of the tipoIdentificacion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setTipoIdentificacion(String value) {
        this.tipoIdentificacion = value;
    }

    /**
     * Gets the value of the identificacion property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIdentificacion() {
        return identificacion;
    }

    /**
     * Sets the value of the identificacion property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setIdentificacion(String value) {
        this.identificacion = value;
    }

    /**
     * Gets the value of the sector property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getSector() {
        return sector;
    }

    /**
     * Sets the value of the sector property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setSector(String value) {
        this.sector = value;
    }

    /**
     * Gets the value of the calificacionHD property.
     *
     * @return 
     */
    public boolean isCalificacionHD() {
        return calificacionHD;
    }

    /**
     * Sets the value of the calificacionHD property.
     *
     * @param value
     */
    public void setCalificacionHD(boolean value) {
        this.calificacionHD = value;
    }

    /**
     * Gets the value of the independiente property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getIndependiente() {
        return independiente;
    }

    /**
     * Sets the value of the independiente property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setIndependiente(String value) {
        this.independiente = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="codigoAmparada" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="franquicia" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="clase" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="marca" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="amparada" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *       &lt;attribute name="garantia" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Caracteristicas {

        @XmlAttribute
        protected String codigoAmparada;
        @XmlAttribute
        protected String franquicia;
        @XmlAttribute
        protected String clase;
        @XmlAttribute
        protected String marca;
        @XmlAttribute(required = true)
        protected boolean amparada;
        @XmlAttribute(required = true)
        protected String garantia;

        /**
         * Gets the value of the codigoAmparada property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getCodigoAmparada() {
            return codigoAmparada;
        }

        /**
         * Sets the value of the codigoAmparada property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setCodigoAmparada(String value) {
            this.codigoAmparada = value;
        }

        /**
         * Gets the value of the franquicia property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getFranquicia() {
            return franquicia;
        }

        /**
         * Sets the value of the franquicia property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setFranquicia(String value) {
            this.franquicia = value;
        }

        /**
         * Gets the value of the clase property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getClase() {
            return clase;
        }

        /**
         * Sets the value of the clase property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setClase(String value) {
            this.clase = value;
        }

        /**
         * Gets the value of the marca property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getMarca() {
            return marca;
        }

        /**
         * Sets the value of the marca property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setMarca(String value) {
            this.marca = value;
        }

        /**
         * Gets the value of the amparada property.
         *
         * @return 
         */
        public boolean isAmparada() {
            return amparada;
        }

        /**
         * Sets the value of the amparada property.
         *
         * @param value
         */
        public void setAmparada(boolean value) {
            this.amparada = value;
        }

        /**
         * Gets the value of the garantia property.
         *
         * @return possible object is {@link String }
         *
         */
        public String getGarantia() {
            return garantia;
        }

        /**
         * Sets the value of the garantia property.
         *
         * @param value allowed object is {@link String }
         *
         */
        public void setGarantia(String value) {
            this.garantia = value;
        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EstadoPlastico">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="EstadoCuenta">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="EstadoOrigen">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="EstadoPago">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="meses" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "estadoPlastico",
        "estadoCuenta",
        "estadoOrigen",
        "estadoPago"
    })
    public static class Estados {

        @XmlElement(name = "EstadoPlastico", required = true)
        protected TarjetaCreditoType.Estados.EstadoPlastico estadoPlastico;
        @XmlElement(name = "EstadoCuenta", required = true)
        protected TarjetaCreditoType.Estados.EstadoCuenta estadoCuenta;
        @XmlElement(name = "EstadoOrigen", required = true)
        protected TarjetaCreditoType.Estados.EstadoOrigen estadoOrigen;
        @XmlElement(name = "EstadoPago", required = true)
        protected TarjetaCreditoType.Estados.EstadoPago estadoPago;

        /**
         * Gets the value of the estadoPlastico property.
         *
         * @return possible object is
         *     {@link TarjetaCreditoType.Estados.EstadoPlastico }
         *
         */
        public TarjetaCreditoType.Estados.EstadoPlastico getEstadoPlastico() {
            return estadoPlastico;
        }

        /**
         * Sets the value of the estadoPlastico property.
         *
         * @param value allowed object is
         *     {@link TarjetaCreditoType.Estados.EstadoPlastico }
         *
         */
        public void setEstadoPlastico(TarjetaCreditoType.Estados.EstadoPlastico value) {
            this.estadoPlastico = value;
        }

        /**
         * Gets the value of the estadoCuenta property.
         *
         * @return possible object is
         *     {@link TarjetaCreditoType.Estados.EstadoCuenta }
         *
         */
        public TarjetaCreditoType.Estados.EstadoCuenta getEstadoCuenta() {
            return estadoCuenta;
        }

        /**
         * Sets the value of the estadoCuenta property.
         *
         * @param value allowed object is
         *     {@link TarjetaCreditoType.Estados.EstadoCuenta }
         *
         */
        public void setEstadoCuenta(TarjetaCreditoType.Estados.EstadoCuenta value) {
            this.estadoCuenta = value;
        }

        /**
         * Gets the value of the estadoOrigen property.
         *
         * @return possible object is
         *     {@link TarjetaCreditoType.Estados.EstadoOrigen }
         *
         */
        public TarjetaCreditoType.Estados.EstadoOrigen getEstadoOrigen() {
            return estadoOrigen;
        }

        /**
         * Sets the value of the estadoOrigen property.
         *
         * @param value allowed object is
         *     {@link TarjetaCreditoType.Estados.EstadoOrigen }
         *
         */
        public void setEstadoOrigen(TarjetaCreditoType.Estados.EstadoOrigen value) {
            this.estadoOrigen = value;
        }

        /**
         * Gets the value of the estadoPago property.
         *
         * @return possible object is
         *     {@link TarjetaCreditoType.Estados.EstadoPago }
         *
         */
        public TarjetaCreditoType.Estados.EstadoPago getEstadoPago() {
            return estadoPago;
        }

        /**
         * Sets the value of the estadoPago property.
         *
         * @param value allowed object is
         *     {@link TarjetaCreditoType.Estados.EstadoPago }
         *
         */
        public void setEstadoPago(TarjetaCreditoType.Estados.EstadoPago value) {
            this.estadoPago = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EstadoCuenta {

            @XmlAttribute(required = true)
            protected String codigo;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fecha;

            /**
             * Gets the value of the codigo property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

            /**
             * Gets the value of the fecha property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EstadoOrigen {

            @XmlAttribute(required = true)
            protected String codigo;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fecha;

            /**
             * Gets the value of the codigo property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

            /**
             * Gets the value of the fecha property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="meses" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EstadoPago {

            @XmlAttribute(required = true)
            protected String codigo;
            @XmlAttribute
            protected Integer meses;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fecha;

            /**
             * Gets the value of the codigo property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

            /**
             * Gets the value of the meses property.
             *
             * @return possible object is {@link Integer }
             *
             */
            public Integer getMeses() {
                return meses;
            }

            /**
             * Sets the value of the meses property.
             *
             * @param value allowed object is {@link Integer }
             *
             */
            public void setMeses(Integer value) {
                this.meses = value;
            }

            /**
             * Gets the value of the fecha property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="codigo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class EstadoPlastico {

            @XmlAttribute(required = true)
            protected String codigo;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fecha;

            /**
             * Gets the value of the codigo property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getCodigo() {
                return codigo;
            }

            /**
             * Sets the value of the codigo property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setCodigo(String value) {
                this.codigo = value;
            }

            /**
             * Gets the value of the fecha property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

        }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained
     * within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Valor" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="moneda" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="saldoActual" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="saldoMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="disponible" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="cuota" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="cupoTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="cuotasMora" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="diasMora" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="fechaPagoCuota" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="fechaLimitePago" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
     *                 &lt;attribute name="calificacion" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "valor"
    })
    public static class Valores {

        @XmlElement(name = "Valor")
        protected TarjetaCreditoType.Valores.Valor valor;

        /**
         * Gets the value of the valor property.
         *
         * @return possible object is {@link TarjetaCreditoType.Valores.Valor }
         *
         */
        public TarjetaCreditoType.Valores.Valor getValor() {
            return valor;
        }

        /**
         * Sets the value of the valor property.
         *
         * @param value allowed object is
         *     {@link TarjetaCreditoType.Valores.Valor }
         *
         */
        public void setValor(TarjetaCreditoType.Valores.Valor value) {
            this.valor = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         *
         * <p>
         * The following schema fragment specifies the expected content
         * contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="moneda" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="saldoActual" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="saldoMora" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="disponible" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="cuota" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="cupoTotal" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="cuotasMora" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="diasMora" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="fechaPagoCuota" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="fechaLimitePago" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="fecha" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
         *       &lt;attribute name="calificacion" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Valor {

            @XmlAttribute
            protected String moneda;
            @XmlAttribute(required = true)
            protected double saldoActual;
            @XmlAttribute(required = true)
            protected double saldoMora;
            @XmlAttribute(required = true)
            protected double disponible;
            @XmlAttribute(required = true)
            protected double cuota;
            @XmlAttribute(required = true)
            protected double cupoTotal;
            @XmlAttribute
            protected Integer cuotasMora;
            @XmlAttribute
            protected Integer diasMora;
            @XmlAttribute
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fechaPagoCuota;
            @XmlAttribute
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fechaLimitePago;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "date")
            protected XMLGregorianCalendar fecha;
            @XmlAttribute
            protected String calificacion;

            /**
             * Gets the value of the moneda property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getMoneda() {
                return moneda;
            }

            /**
             * Sets the value of the moneda property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setMoneda(String value) {
                this.moneda = value;
            }

            /**
             * Gets the value of the saldoActual property.
             *
             * @return 
             */
            public double getSaldoActual() {
                return saldoActual;
            }

            /**
             * Sets the value of the saldoActual property.
             *
             * @param value
             */
            public void setSaldoActual(double value) {
                this.saldoActual = value;
            }

            /**
             * Gets the value of the saldoMora property.
             *
             * @return 
             */
            public double getSaldoMora() {
                return saldoMora;
            }

            /**
             * Sets the value of the saldoMora property.
             *
             * @param value
             */
            public void setSaldoMora(double value) {
                this.saldoMora = value;
            }

            /**
             * Gets the value of the disponible property.
             *
             * @return 
             */
            public double getDisponible() {
                return disponible;
            }

            /**
             * Sets the value of the disponible property.
             *
             * @param value
             */
            public void setDisponible(double value) {
                this.disponible = value;
            }

            /**
             * Gets the value of the cuota property.
             *
             * @return 
             */
            public double getCuota() {
                return cuota;
            }

            /**
             * Sets the value of the cuota property.
             *
             * @param value
             */
            public void setCuota(double value) {
                this.cuota = value;
            }

            /**
             * Gets the value of the cupoTotal property.
             *
             * @return 
             */
            public double getCupoTotal() {
                return cupoTotal;
            }

            /**
             * Sets the value of the cupoTotal property.
             *
             * @param value
             */
            public void setCupoTotal(double value) {
                this.cupoTotal = value;
            }

            /**
             * Gets the value of the cuotasMora property.
             *
             * @return possible object is {@link Integer }
             *
             */
            public Integer getCuotasMora() {
                return cuotasMora;
            }

            /**
             * Sets the value of the cuotasMora property.
             *
             * @param value allowed object is {@link Integer }
             *
             */
            public void setCuotasMora(Integer value) {
                this.cuotasMora = value;
            }

            /**
             * Gets the value of the diasMora property.
             *
             * @return possible object is {@link Integer }
             *
             */
            public Integer getDiasMora() {
                return diasMora;
            }

            /**
             * Sets the value of the diasMora property.
             *
             * @param value allowed object is {@link Integer }
             *
             */
            public void setDiasMora(Integer value) {
                this.diasMora = value;
            }

            /**
             * Gets the value of the fechaPagoCuota property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFechaPagoCuota() {
                return fechaPagoCuota;
            }

            /**
             * Sets the value of the fechaPagoCuota property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFechaPagoCuota(XMLGregorianCalendar value) {
                this.fechaPagoCuota = value;
            }

            /**
             * Gets the value of the fechaLimitePago property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFechaLimitePago() {
                return fechaLimitePago;
            }

            /**
             * Sets the value of the fechaLimitePago property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFechaLimitePago(XMLGregorianCalendar value) {
                this.fechaLimitePago = value;
            }

            /**
             * Gets the value of the fecha property.
             *
             * @return possible object is {@link XMLGregorianCalendar }
             *
             */
            public XMLGregorianCalendar getFecha() {
                return fecha;
            }

            /**
             * Sets the value of the fecha property.
             *
             * @param value allowed object is {@link XMLGregorianCalendar }
             *
             */
            public void setFecha(XMLGregorianCalendar value) {
                this.fecha = value;
            }

            /**
             * Gets the value of the calificacion property.
             *
             * @return possible object is {@link String }
             *
             */
            public String getCalificacion() {
                return calificacion;
            }

            /**
             * Sets the value of the calificacion property.
             *
             * @param value allowed object is {@link String }
             *
             */
            public void setCalificacion(String value) {
                this.calificacion = value;
            }

        }

    }

}
